//Gold: #F0BA36

//Composite: #FFFFFF
//Earth: #D4880F
//Fire: #C40000
//Water: #01A2FF
//Nature: #00C400
//Light: #E5DE23
//Dark: #8433C8


"addon_game_name"											"Element TD"
"npc_dota_hero_wisp"										"Builder"
"npc_dota_hero_keeper_of_the_light"							"Builder"

"DOTA_Tooltip_ability_prev_page"							"Previous Page"
"DOTA_Tooltip_ability_next_page"							"Next Page"
"DOTA_Tooltip_ability_prev_page_tower"						"Back"
"DOTA_Tooltip_ability_next_page_tower"						"Next"

"basic_arrow_tower"											"Arrow Tower"
"advanced_arrow_tower"										"Advanced Arrow Tower"
"super_arrow_tower"											"Super Arrow Tower"

"basic_cannon_tower"										"Cannon Tower"
"advanced_cannon_tower"										"Advanced Cannon Tower"
"super_cannon_tower"										"Super Cannon Tower"

"water_tower"												"Water Tower"
"amplified_water_tower"										"Amplified Water Tower"
"focused_water_tower"										"Focused Water Tower"
"refined_water_tower"										"Refined Water Tower"
"pure_water_tower"											"Pure Water Tower"

"fire_tower"												"Fire Tower"
"amplified_fire_tower"										"Amplified Fire Tower"
"focused_fire_tower"										"Focused Fire Tower"
"refined_fire_tower"										"Refined Fire Tower"
"pure_fire_tower"											"Pure Fire Tower"

"nature_tower"												"Nature Tower"
"amplified_nature_tower"									"Amplified Nature Tower"
"focused_nature_tower"										"Focused Nature Tower"
"refined_nature_tower"										"Refined Nature Tower"
"pure_nature_tower"											"Pure Nature Tower"

"earth_tower"												"Earth Tower"
"amplified_earth_tower"										"Amplified Earth Tower"
"focused_earth_tower"										"Focused Earth Tower"
"refined_earth_tower"										"Refined Earth Tower"
"pure_earth_tower"											"Pure Earth Tower"

"light_tower"												"Light Tower"
"amplified_light_tower"										"Amplified Light Tower"
"focused_light_tower"										"Focused Light Tower"
"refined_light_tower"										"Refined Light Tower"
"pure_light_tower"											"Pure Light Tower"

"dark_tower"												"Dark Tower"
"amplified_dark_tower"										"Amplified Dark Tower"
"focused_dark_tower"										"Focused Dark Tower"
"refined_dark_tower"										"Refined Dark Tower"
"pure_dark_tower"											"Pure Dark Tower"

"magic_tower"												"Magic Tower"
"magic_tower_2"												"Sorcery Tower"
"magic_tower_3"												"Wizardry Tower"

"disease_tower"												"Disease Tower"
"disease_tower_2"											"Decay Tower"
"disease_tower_3"											"Death Tower"

"well_tower"												"Well Tower"
"well_tower_2"												"Spring Tower"
"well_tower_3"												"Waterfall Tower"

"blacksmith_tower"											"Blacksmith Tower"
"blacksmith_tower_2"										"Forge Tower"
"blacksmith_tower_3"										"Foundry Tower"

"mushroom_tower"											"Mushroom Tower"
"mushroom_tower_2"											"Toadstool Tower"
"mushroom_tower_3"											"Fungus Tower"

"quark_tower"												"Quark Tower"
"quark_tower_2"												"Electron Tower"
"quark_tower_3"												"Atom Tower"

"electricity_tower"											"Electricity Tower"
"electricity_tower_2"										"Lightning Tower"
"electricity_tower_3"										"Energy Tower"

"flame_tower"												"Flame Tower"
"flame_tower_2"												"Solar Tower"
"flame_tower_3"												"Sun Tower"

"vapor_tower"												"Vapor Tower"
"vapor_tower_2"												"Mist Tower"
"vapor_tower_3"												"Steam Tower"

"poison_tower"												"Poison Tower"
"poison_tower_2"											"Pollution Tower"
"poison_tower_3"											"Pestilence Tower"

"life_tower"												"Life Tower"
"life_tower_2"												"Eternal Tower"
"life_tower_3"												"Soul Catcher Tower"

"hydro_tower"												"Hydro Tower"
"hydro_tower_2"												"Spout Tower"
"hydro_tower_3"												"Geyser Tower"

"trickery_tower"											"Trickery Tower"
"trickery_tower_2"											"Mirage Tower"
"trickery_tower_3"											"Eidolon Tower"

"gunpowder_tower"											"Gunpowder Tower"
"gunpowder_tower_2"											"Mortar Tower"
"gunpowder_tower_3"											"Vulcan Tower"

"ice_tower"													"Ice Tower"
"ice_tower_2"												"Freezing Tower"
"ice_tower_3"												"Subzero Tower"

"muck_tower"												"Muck Tower"
"muck_tower_2"												"Mire Tower"

"gold_tower"												"Gold Tower"
"gold_tower_2"												"Wealth Tower"

"windstorm_tower"											"Windstorm Tower"
"windstorm_tower_2"											"Monsoon Tower"

"quake_tower"												"Quake Tower"
"quake_tower_2"												"Earthbreaker Tower"

"enchantment_tower"											"Enchantment Tower"
"enchantment_tower_2"										"Incantation Tower"

"flooding_tower"											"Flooding Tower"
"flooding_tower_2"											"Drowning Tower"

"laser_tower"												"Laser Tower"
"laser_tower_2"												"Phaser Tower"

"hail_tower"												"Hail Tower"
"hail_tower_2"												"Comet Tower"

"runic_tower"												"Runic Tower"
"runic_tower_2"												"Occult Tower"

"impulse_tower"												"Impulse Tower"
"impulse_tower_2"											"Velocity Tower"

"obliteration_tower"										"Obliteration Tower"
"obliteration_tower_2"										"Annihilation Tower"

"ephemeral_tower"											"Ephemeral Tower"
"ephemeral_tower_2"											"Temporal Tower"

"flamethrower_tower"										"Flamethrower Tower"
"flamethrower_tower_2"										"Flamespewer Tower"

"haste_tower"												"Haste Tower"
"haste_tower_2"												"Blitz Tower"

"torrent_tower"												"Torrent Tower"
"torrent_tower_2"											"Tsunami Tower"

"roots_tower"												"Roots Tower"
"roots_tower_2"												"Thorns Tower"

"nova_tower"												"Nova Tower"
"nova_tower_2"												"Supernova Tower"

"erosion_tower"												"Erosion Tower"
"erosion_tower_2"											"Corrosion Tower"

"polar_tower"												"Polar Tower"
"polar_tower_2"												"Glacial Tower"

"jinx_tower"												"Jinx Tower"
"jinx_tower_2"												"Hex Tower"



"DOTA_Tooltip_ability_upgrade_tower"						"Upgrade Tower"
"DOTA_Tooltip_ability_upgrade_tower_Description"			"Opens a list of upgrades that can be applied to this tower."

"DOTA_Tooltip_ability_sell_tower_100"						"Sell Tower"
"DOTA_Tooltip_ability_sell_tower_100_Description"			"Sells this tower, returning a percentage of it's total cost to the owner."
"DOTA_Tooltip_ability_sell_tower_100_sell_amount_tooltip"	"%GOLD RETURNED:"
	
"DOTA_Tooltip_ability_sell_tower_75"						"Sell Tower"
"DOTA_Tooltip_ability_sell_tower_75_Description"			"Sells this tower, returning a percentage of it's total cost to the owner."
"DOTA_Tooltip_ability_sell_tower_75_sell_amount_tooltip"	"%GOLD RETURNED:"

"DOTA_Tooltip_ability_sell_tower_0"							"Sell Tower"
"DOTA_Tooltip_ability_sell_tower_0_Description"				"Sells this tower, returning a percentage of it's total cost to the owner."
"DOTA_Tooltip_ability_sell_tower_0_sell_amount_tooltip"		"%GOLD RETURNED:"

"DOTA_Tooltip_ability_splash_damage_orb"					"Splash Damage"
"DOTA_Tooltip_ability_splash_damage_orb_Description"		"This tower's attacks deal damage in an area from where they land."

"DOTA_Tooltip_ability_build_arrow_tower"					"Build Arrow Tower"
"DOTA_Tooltip_ability_build_arrow_tower_Description"		"Builds a basic level 1 Arrow Tower at the specified location.\n\nCOST: <font color='#F0BA36'>7 Gold</font>\n\nELEMENT: <font color='#FFFFFF'>None</font> \nDAMAGE TYPE: <font color='#FFFFFF'>Composite</font> \nDAMAGE: <font color='#FFFFFF'>3</font> \nRANGE: <font color='#FFFFFF'>750</font> \nSPEED: <font color='#FFFFFF'>0.66</font>"

"DOTA_Tooltip_ability_build_cannon_tower"					"Build Cannon Tower"
"DOTA_Tooltip_ability_build_cannon_tower_Description"		"Builds a basic level 1 Cannon Tower at the specified location.\n\nCOST: <font color='#F0BA36'>7 Gold</font>\n\nELEMENT: <font color='#FFFFFF'>None</font> \nDAMAGE TYPE: <font color='#FFFFFF'>Composite</font> \nDAMAGE: <font color='#FFFFFF'>9</font> \nRANGE: <font color='#FFFFFF'>600</font> \nSPEED: <font color='#FFFFFF'>1.5</font> \nAOE: <font color='#FFFFFF'>100 Full/200 Half</font>"

"DOTA_Tooltip_ability_build_water_tower"					"Build Water Tower"
"DOTA_Tooltip_ability_build_water_tower_Description"		"Builds a level 1 Water Tower at the specified location.\n<font color='#F0BA36'>Requires: </font><font color='#01A2FF'>Water</font>\n\nCOST: <font color='#F0BA36'>175 Gold</font>\n\nELEMENT: <font color='#01A2FF'>Water</font> \nDAMAGE TYPE: <font color='#01A2FF'>Water</font> \nDAMAGE: <font color='#FFFFFF'>24</font> \nRANGE: <font color='#FFFFFF'>750</font> \nSPEED: <font color='#FFFFFF'>0.31</font> \nAOE: <font color='#FFFFFF'>100 Full/200 Half</font>"

"DOTA_Tooltip_ability_build_fire_tower"						"Build Fire Tower"
"DOTA_Tooltip_ability_build_fire_tower_Description"			"Builds a level 1 Fire Tower at the specified location.\n<font color='#F0BA36'>Requires: </font><font color='#C40000'>Fire</font>\n\nCOST: <font color='#F0BA36'>175 Gold</font>\n\nELEMENT: <font color='#C40000'>Fire</font> \nDAMAGE TYPE: <font color='#C40000'>Fire</font> \nDAMAGE: <font color='#FFFFFF'>21</font> \nRANGE: <font color='#FFFFFF'>500</font> \nSPEED: <font color='#FFFFFF'>0.31</font> \nAOE: <font color='#FFFFFF'>150 Full/300 Half</font>"

"DOTA_Tooltip_ability_build_nature_tower"					"Build Nature Tower"
"DOTA_Tooltip_ability_build_nature_tower_Description"		"Builds a level 1 Nature Tower at the specified location.\n<font color='#F0BA36'>Requires: </font><font color='#00C400'>Nature</font>\n\nCOST: <font color='#F0BA36'>175 Gold</font>\n\nELEMENT: <font color='#00C400'>Nature</font> \nDAMAGE TYPE: <font color='#00C400'>Nature</font> \nDAMAGE: <font color='#FFFFFF'>123</font> \nSPEED: <font color='#FFFFFF'>0.66</font> \nRANGE: <font color='#FFFFFF'>625</font>"

"DOTA_Tooltip_ability_build_earth_tower"					"Build Earth Tower"
"DOTA_Tooltip_ability_build_earth_tower_Description"		"Builds a level 1 Earth Tower at the specified location.\n<font color='#F0BA36'>Requires: </font><font color='#D4880F'>Earth</font>\n\nCOST: <font color='#F0BA36'>175 Gold</font>\n\nELEMENT: <font color='#D4880F'>Earth</font> \nDAMAGE TYPE: <font color='#D4880F'>Earth</font> \nDAMAGE: <font color='#FFFFFF'>54</font> \nSPEED: <font color='#FFFFFF'>1</font> \nRANGE: <font color='#FFFFFF'>625</font> \nAOE: <font color='#FFFFFF'>150 Full/300 Half</font>"

"DOTA_Tooltip_ability_build_light_tower"					"Build Light Tower"
"DOTA_Tooltip_ability_build_light_tower_Description"		"Builds a level 1 Light Tower at the specified location.\n<font color='#F0BA36'>Requires: </font><font color='#E5DE23'>Light</font>\n\nCOST: <font color='#F0BA36'>175 Gold</font>\n\nELEMENT: <font color='#E5DE23'>Light</font> \nDAMAGE TYPE: <font color='#E5DE23'>Light</font> \nDAMAGE: <font color='#FFFFFF'>84</font> \nSPEED: <font color='#FFFFFF'>0.66</font> \nRANGE: <font color='#FFFFFF'>1375</font>"

"DOTA_Tooltip_ability_build_dark_tower"						"Build Dark Tower"
"DOTA_Tooltip_ability_build_dark_tower_Description"			"Builds a level 1 Dark Tower at the specified location.\n<font color='#F0BA36'>Requires: </font><font color='#8433C8'>Dark</font>\n\nCOST: <font color='#F0BA36'>175 Gold</font>\n\nELEMENT: <font color='#8433C8'>Dark</font> \nDAMAGE TYPE: <font color='#8433C8'>Dark</font> \nDAMAGE: <font color='#FFFFFF'>240</font> \nSPEED: <font color='#FFFFFF'>1.5</font> \nRANGE: <font color='#FFFFFF'>1000</font>"

//================//
//==Damage Types==//
//================//

"fire"		"Fire"
"water"		"Water"
"earth"		"Earth"
"nature"	"Nature"
"light"		"Light"
"dark"		"Dark"
"none"		"None"
"composite"	"Composite"


"DOTA_Tooltip_ability_composite_passive"					"Composite"
"DOTA_Tooltip_ability_composite_passive_Description"		"This tower deals <font color='#FFFFFF'>Composite<font> damage, affecting all element types the same."
"DOTA_Tooltip_ability_composite_passive_aoe"				"Composite"
"DOTA_Tooltip_ability_composite_passive_aoe_Description"	"This tower deals <font color='#FFFFFF'>Composite<font> damage, affecting all element types the same."

"DOTA_Tooltip_ability_fire_passive"							"Fire"
"DOTA_Tooltip_ability_fire_passive_Description"				"This tower deals <font color='#C40000'>Fire</font> damage. \n\nDeals 200%% damage to <font color='#00C400'>Nature</font>.\nDeals 50%% damage to <font color='#01A2FF'>Water</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
"DOTA_Tooltip_ability_fire_passive_aoe"						"Fire"
"DOTA_Tooltip_ability_fire_passive_aoe_Description"			"This tower deals <font color='#C40000'>Fire</font> damage. \n\nDeals 200%% damage to <font color='#00C400'>Nature</font>.\nDeals 50%% damage to <font color='#01A2FF'>Water</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."

"DOTA_Tooltip_ability_water_passive"						"Water"
"DOTA_Tooltip_ability_water_passive_Description"			"This tower deals <font color='#01A2FF'>Water</font> damage. \n\nDeals 200%% damage to <font color='#C40000'>Fire</font>.\nDeals 50%% damage to <font color='#8433C8'>Dark</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
"DOTA_Tooltip_ability_water_passive_aoe"					"Water"
"DOTA_Tooltip_ability_water_passive_aoe_Description"		"This tower deals <font color='#01A2FF'>Water</font> damage. \n\nDeals 200%% damage to <font color='#C40000'>Fire</font>.\nDeals 50%% damage to <font color='#8433C8'>Dark</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."

"DOTA_Tooltip_ability_nature_passive"						"Nature"
"DOTA_Tooltip_ability_nature_passive_Description"			"This tower deals <font color='#00C400'>Nature</font> damage. \n\nDeals 200%% damage to <font color='#D4880F'>Earth</font>.\nDeals 50%% damage to <font color='#C40000'>Fire</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
"DOTA_Tooltip_ability_nature_passive_aoe"					"Nature"
"DOTA_Tooltip_ability_nature_passive_aoe_Description"		"This tower deals <font color='#00C400'>Nature</font> damage. \n\nDeals 200%% damage to <font color='#D4880F'>Earth</font>.\nDeals 50%% damage to <font color='#C40000'>Fire</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."

"DOTA_Tooltip_ability_earth_passive"						"Earth"
"DOTA_Tooltip_ability_earth_passive_Description"			"This tower deals <font color='#D4880F'>Earth</font> damage. \n\nDeals 200%% damage to <font color='#E5DE23'>Light</font>.\nDeals 50%% damage to <font color='#00C400'>Nature</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
"DOTA_Tooltip_ability_earth_passive_aoe"					"Earth"
"DOTA_Tooltip_ability_earth_passive_aoe_Description"		"This tower deals <font color='#D4880F'>Earth</font> damage. \n\nDeals 200%% damage to <font color='#E5DE23'>Light</font>.\nDeals 50%% damage to <font color='#00C400'>Nature</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."

"DOTA_Tooltip_ability_light_passive"						"Light"
"DOTA_Tooltip_ability_light_passive_Description"			"This tower deals <font color='#E5DE23'>Light</font> damage. \n\nDeals 200%% damage to <font color='#8433C8'>Dark</font>.\nDeals 50%% damage to <font color='#D4880F'>Earth</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
"DOTA_Tooltip_ability_light_passive_aoe"					"Light"
"DOTA_Tooltip_ability_light_passive_aoe_Description"		"This tower deals <font color='#E5DE23'>Light</font> damage. \n\nDeals 200%% damage to <font color='#8433C8'>Dark</font>.\nDeals 50%% damage to <font color='#D4880F'>Earth</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."

"DOTA_Tooltip_ability_dark_passive"							"Dark"
"DOTA_Tooltip_ability_dark_passive_Description"				"This tower deals <font color='#8433C8'>Dark</font> damage. \n\nDeals 200%% damage to <font color='#01A2FF'>Water</font>.\nDeals 50%% damage to <font color='#E5DE23'>Light</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
"DOTA_Tooltip_ability_dark_passive_aoe"						"Dark"
"DOTA_Tooltip_ability_dark_passive_aoe_Description"			"This tower deals <font color='#8433C8'>Dark</font> damage. \n\nDeals 200%% damage to <font color='#01A2FF'>Water</font>.\nDeals 50%% damage to <font color='#E5DE23'>Light</font>.\nDeals 90%% damage to <font color='#FFFFFF'>Composite</font>."
		
//===============//
//==Armor Types==//
//===============// 

"DOTA_Tooltip_ability_composite_armor"						"Composite Armor"
"DOTA_Tooltip_ability_composite_armor_Description"			"This creep takes 100%% <font color='#FFFFFF'>Composite</font> damage and 90%% from all other elements."
"DOTA_Tooltip_composite_armor"								"Composite Armor"
"DOTA_Tooltip_composite_armor_Description"					"100%% damage from Composite\n90%% damage from other Elements"

"DOTA_Tooltip_ability_fire_armor"							"Fire Armor"
"DOTA_Tooltip_ability_fire_armor_Description"				"200%% damage from <font color='#01A2FF'>Water</font>\n50%% damage from <font color='#00C400'>Nature</font>"
"DOTA_Tooltip_fire_armor"									"Fire Armor"
"DOTA_Tooltip_fire_armor_Description"						"200%% damage from <font color='#01A2FF'>Water</font>\n50%% damage from <font color='#00C400'>Nature</font>"

"DOTA_Tooltip_ability_nature_armor"							"Nature Armor"
"DOTA_Tooltip_ability_nature_armor_Description"				"200%% damage from <font color='#C40000'>Fire</font>\n50%% damage from <font color='#D4880F'>Earth</font>"
"DOTA_Tooltip_nature_armor"									"Nature Armor"
"DOTA_Tooltip_nature_armor_Description"						"200%% damage from <font color='#C40000'>Fire</font>\n50%% damage from <font color='#D4880F'>Earth</font>"

"DOTA_Tooltip_ability_water_armor"							"Water Armor"
"DOTA_Tooltip_ability_water_armor_Description"				"200%% damage from <font color='#8433C8'>Dark</font>\n50%% damage from <font color='#C40000'>Fire</font>"
"DOTA_Tooltip_water_armor"									"Water Armor"
"DOTA_Tooltip_water_armor_Description"						"200%% damage from <font color='#8433C8'>Dark</font>\n50%% damage from <font color='#C40000'>Fire</font>"

"DOTA_Tooltip_ability_earth_armor"							"Earth Armor"
"DOTA_Tooltip_ability_earth_armor_Description"				"200%% damage from <font color='#00C400'>Nature</font>\n50%% damage from <font color='#E5DE23'>Light</font>"
"DOTA_Tooltip_earth_armor"									"Earth Armor"
"DOTA_Tooltip_earth_armor_Description"						"200%% damage from <font color='#00C400'>Nature</font>\n50%% damage from <font color='#E5DE23'>Light</font>"

"DOTA_Tooltip_ability_light_armor"							"Light Armor"
"DOTA_Tooltip_ability_light_armor_Description"				"200%% damage from <font color='#D4880F'>Earth</font>\n50%% damage from <font color='#8433C8'>Dark</font>"
"DOTA_Tooltip_light_armor"									"Light Armor"
"DOTA_Tooltip_light_armor_Description"						"200%% damage from <font color='#D4880F'>Earth</font>\n50%% damage from <font color='#8433C8'>Dark</font>"

"DOTA_Tooltip_ability_dark_armor"							"Dark Armor"
"DOTA_Tooltip_ability_dark_armor_Description"				"200%% damage from <font color='#E5DE23'>Light</font>\n50%% damage from <font color='#01A2FF'>Water</font>"
"DOTA_Tooltip_dark_armor"									"Dark Armor"
"DOTA_Tooltip_dark_armor_Description"						"200%% damage from <font color='#E5DE23'>Light</font>\n50%% damage from <font color='#01A2FF'>Water</font>"

"DOTA_Tooltip_modifier_creep_armor_buff"					"Physical Armor"
"DOTA_Tooltip_modifier_creep_armor_buff_Description"		"Each point of Physical Armor equal 1%% damage block. Physical Armor varies with difficulty."
		
//======================//
//===Summon Elementals==//
//======================//

"DOTA_Tooltip_ability_summon_water_elemental"				"Summon Water Elemental"
"DOTA_Tooltip_ability_summon_water_elemental_Description"	"Summons a <font color='#01A2FF'>Water</font> Elemental. Killing it will grant you one <font color='#01A2FF'>Water Essence</font>, allowing you to build <font color='#01A2FF'>Water</font> towers. You can summon up to 3 elementals of each type.\n\nSummoning before the first wave begins grants you the essence directly.\n\n<font color='#F0BA36'>Costs 1 Lumber</font>\n"
"DOTA_Tooltip_ability_summon_water_elemental_level"			"ELEMENTAL LEVEL:"
"DOTA_Tooltip_ability_summon_water_elemental_health"		"BASE HEALTH:"

"DOTA_Tooltip_ability_summon_fire_elemental"				"Summon Fire Elemental"
"DOTA_Tooltip_ability_summon_fire_elemental_Description"	"Summons a <font color='#C40000'>Fire</font> Elemental. Killing it will grant you one <font color='#C40000'>Fire Essence</font>, allowing you to build <font color='#C40000'>Fire</font> towers. You can summon up to 3 elementals of each type.\n\nSummoning before the first wave begins grants you the essence directly.\n\n<font color='#F0BA36'>Costs 1 Lumber</font>\n"
"DOTA_Tooltip_ability_summon_fire_elemental_level"			"ELEMENTAL LEVEL:"
"DOTA_Tooltip_ability_summon_fire_elemental_health"			"BASE HEALTH:"

"DOTA_Tooltip_ability_summon_nature_elemental"				"Summon Nature Elemental"
"DOTA_Tooltip_ability_summon_nature_elemental_Description"	"Summons a <font color='#00C400'>Nature</font> Elemental. Killing it will grant you one <font color='#00C400'>Nature Essence</font>, allowing you to build <font color='#00C400'>Nature</font> towers. You can summon up to 3 elementals of each type.\n\nSummoning before the first wave begins grants you the essence directly.\n\n<font color='#F0BA36'>Costs 1 Lumber</font>\n"
"DOTA_Tooltip_ability_summon_nature_elemental_level"		"ELEMENTAL LEVEL:"
"DOTA_Tooltip_ability_summon_nature_elemental_health"		"BASE HEALTH:"

"DOTA_Tooltip_ability_summon_earth_elemental"				"Summon Earth Elemental"
"DOTA_Tooltip_ability_summon_earth_elemental_Description"	"Summons an <font color='#D4880F'>Earth</font> Elemental. Killing it will grant you one <font color='#D4880F'>Earth Essence</font>, allowing you to build <font color='#D4880F'>Earth</font> towers. You can summon up to 3 elementals of each type.\n\nSummoning before the first wave begins grants you the essence directly.\n\n<font color='#F0BA36'>Costs 1 Lumber</font>\n"
"DOTA_Tooltip_ability_summon_earth_elemental_level"			"ELEMENTAL LEVEL:"
"DOTA_Tooltip_ability_summon_earth_elemental_health"		"BASE HEALTH:"

"DOTA_Tooltip_ability_summon_light_elemental"				"Summon Light Elemental"
"DOTA_Tooltip_ability_summon_light_elemental_Description"	"Summons a <font color='#E5DE23'>Light</font> Elemental. Killing it will grant you one <font color='#E5DE23'>Light Essence</font>, allowing you to build <font color='#E5DE23'>Light</font> towers. You can summon up to 3 elementals of each type.\n\nSummoning before the first wave begins grants you the essence directly.\n\n<font color='#F0BA36'>Costs 1 Lumber</font>\n"
"DOTA_Tooltip_ability_summon_light_elemental_level"			"ELEMENTAL LEVEL:"
"DOTA_Tooltip_ability_summon_light_elemental_health"		"BASE HEALTH:"

"DOTA_Tooltip_ability_summon_dark_elemental"				"Summon Dark Elemental"
"DOTA_Tooltip_ability_summon_dark_elemental_Description"	"Summons a <font color='#8433C8'>Dark</font> Elemental. Killing it will grant you one <font color='#8433C8'>Dark Essence</font>, allowing you to build <font color='#8433C8'>Dark</font> towers. You can summon up to 3 elementals of each type.\n\nSummoning before the first wave begins grants you the essence directly.\n\n<font color='#F0BA36'>Costs 1 Lumber</font>\n"
"DOTA_Tooltip_ability_summon_dark_elemental_level"			"ELEMENTAL LEVEL:"
"DOTA_Tooltip_ability_summon_dark_elemental_health"			"BASE HEALTH:"

//=================//
//===Creep Spells==//
//=================//

"DOTA_Tooltip_ability_creep_ability_heal"						"Heal"
"DOTA_Tooltip_ability_creep_ability_heal_Description"			"Upon death, this creep heals all other creeps in a small area around it by a percentage of their max health."
"DOTA_Tooltip_ability_creep_ability_heal_heal_amount"			"%HEAL AMOUNT:"
"DOTA_Tooltip_ability_creep_ability_heal_aoe"					"RADIUS:"

"DOTA_Tooltip_ability_creep_ability_fast"						"Haste"
"DOTA_Tooltip_ability_creep_ability_fast_Description"			"After spawning, this creep will gain max movement speed for a short duration after a random period of time. After that, it will gain max movement speed at a fixed interval.."
"DOTA_Tooltip_ability_creep_ability_fast_duration"				"DURATION:"
"DOTA_Tooltip_ability_creep_ability_fast_interval_tooltip"		"INTERVAL:"

"DOTA_Tooltip_ability_creep_ability_undead"						"Reanimate"
"DOTA_Tooltip_ability_creep_ability_undead_Description"			"Upon death, this creep will respawn after a short delay at a percentage of their max health."
"DOTA_Tooltip_ability_creep_ability_undead_delay"				"RESPAWN DELAY:"
"DOTA_Tooltip_ability_creep_ability_undead_health"				"%REMAINING HEALTH:"

"DOTA_Tooltip_ability_creep_ability_mechanical"					"Mechanical"
"DOTA_Tooltip_ability_creep_ability_mechanical_Description"		"After spawning, this creep will gain invulnerability for a short duration after a random period of time. After the first invulnerability instance, it will become invulnerable at fixed intervals."
"DOTA_Tooltip_ability_creep_ability_mechanical_duration"		"DURATION:"
"DOTA_Tooltip_ability_creep_ability_mechanical_interval"		"INTERVAL:"

"DOTA_Tooltip_ability_creep_ability_image"						"Image"
"DOTA_Tooltip_ability_creep_ability_image_Description"			"This creep spawns an image of itself when it takes damage. Can only trigger once every 10 seconds. Images do not leak and give no bounty."
"DOTA_Tooltip_ability_creep_ability_image_duration"				"IMAGE DURATION:"

//=============//
//====Units====//
//=============//

"elemental_summoner"		"Elemental Summoner"
"water_elemental"			"Water Elemental"
"fire_elemental"			"Fire Elemental"
"nature_elemental"			"Nature Elemental"
"earth_elemental"			"Earth Elemental"
"light_elemental"			"Light Elemental"
"dark_elemental"			"Dark Elemental"

"timber_wolf"			"Timber Wolf"
"potato_bear"			"Potato Bear"
"satyr_trickster"		"Satyr Trickster"
"ghoul"					"Ghoul"
"forest_troll"			"Forest Troll"
"quillboar"				"Quillboar"
"deepseer"				"Naga Deepseer"
"succubus"				"Succubus"
"undead_treant"			"Undead Treant"
"paladin"				"Paladin"
"centaur"				"Centaur"
"sludge_minion"			"Eidolon"
"naga_myrmidon"			"Naga Myrmidon"
"fel_beast"				"Fel Beast"
"crystal_arachnid"		"Crystal Arachnid"
"dark_minion"			"Dark Seer"
"badger"				"Badger"
"rogue_knight"			"Rogue Knight"
"priest"				"Priest"
"siege_catapult"		"Siege Catapult"
"fire_revenant"			"Fire Revenant"
"bandit"				"Bandit"
"corrupted_treant"		"Corrupted Treant"	
"battleship"			"Battleship"
"doomguard"				"Doomguard"
"fel_guard"				"Fel Guard"
"snowy_owl"				"Snowy Owl"
"furbolg_tracker"		"Furbolg Tracker"
"draenei_protector"		"Draenei Protector"
"plague_rat"			"Plague Rat"
"admiral"				"Admiral"
"goblin_shredder"		"Goblin Shredder"
"giant_spider"			"Giant Spider"
"red_dragon"			"Red Dragon"
"shadow_wolf"			"Shadow Wolf"
"parrot"				"Parrot"
"lockjaw"				"Lockjaw"
"battle_golem"			"Battle Golem"
"kobold_shoveler"		"Kobold"
"thunder_lizard"		"Thunder Lizard"
"sea_dragon"			"Sea Dragon"
"dreadlord"				"Dreadlord"
"sand_lobster"			"Sand Lobster"
"wisp"					"Wisp"
"vengeful_spirit"		"Vengeful Spirit"
"demolisher"			"Demolisher"
"octopus"				"Octopus"
"ghost"					"Ghost"
"black_drake"			"Black Drake"
"mechanical_mediary"	"Mechanical Mediary"
"harpy_rogue"			"Harpy Rouge"
"batrider"				"Batrider"
"archmage"				"Archmage"
"green_dragon"			"Green Dragon"
"leviathan"				"Leviathan"
"dragon_knight"			"Dragon Knight"
"lava_runner"			"Lava Runner"
"infernal_contraption"	"Infernal Contraption"
"mountain_giant"		"Mountain Giant"
"necrolyte"				"Necrolyte"
"icefrog"				"Icefrog"

"DOTA_Tooltip_ability_show_tower_range"							"Show Tower Range"
"DOTA_Tooltip_ability_show_tower_range_Description"				"For WindStrike. Cast on a tower to view its attack range. Range indicator lasts for 10 seconds."

//=================//
//===Tower Spells==//
//=================//
"DOTA_Tooltip_modifier_support_tower"							"Support Tower"
"DOTA_Tooltip_modifier_support_tower_Description"				"This tower is a support tower. It can not be buffed by other support towers."

///////////////////////////////
"magic_tower_ability"											"Increase/Decrease Range"
"magic_tower_ability_desc"										"You can increase or decrease this tower's attack range manually. Longer range means less damage and vice versa."

"DOTA_Tooltip_modifier_magic_tower_attack_range"					"Range"
"DOTA_Tooltip_modifier_magic_tower_attack_range_Description"		"Tower attack range is %dMODIFIER_PROPERTY_ATTACK_RANGE_BONUS%."

"DOTA_Tooltip_ability_magic_tower_increase_range"					"Increase Range"
"DOTA_Tooltip_ability_magic_tower_increase_range_Description"		"Increase this tower's attack range. Longer range means less bonus damage."
"DOTA_Tooltip_ability_magic_tower_increase_range_range"				"BONUS RANGE:"
"DOTA_Tooltip_ability_magic_tower_increase_range_damage_reduction"	"%DAMAGE REDUCTION:"

"DOTA_Tooltip_ability_magic_tower_decrease_range"					"Decrease Range"
"DOTA_Tooltip_ability_magic_tower_decrease_range_Description"		"Decrease this tower's attack range. Shorter range means more bonus damage."
"DOTA_Tooltip_ability_magic_tower_decrease_range_range"				"BONUS RANGE:"
"DOTA_Tooltip_ability_magic_tower_decrease_range_damage_reduction"	"%DAMAGE REDUCTION:"

///////////////////////////////
"disease_tower_ability"											"Soul Reaper"
"disease_tower_ability_desc"									"Preys on the life force of enemies, causing this tower to deal damage based on the percent of the creep's remaining health. The lower the health, the more damage is dealt."

"DOTA_Tooltip_ability_disease_tower_soul_reaper"				"Soul Reaper"
"DOTA_Tooltip_ability_disease_tower_soul_reaper_Description"	"Preys on the life force of enemies, causing this tower to deal damage based on the percent of the creep's remaining health. The lower the health, the more damage is dealt."

///////////////////////////////
"well_tower_ability"											"Spring Forward"
"well_tower_ability_desc"										"Increases a non-support tower's attack speed for a duration."

"DOTA_Tooltip_modifier_spring_forward"							"Spring Forward"
"DOTA_Tooltip_modifier_spring_forward_Description"				"Buffed by a Well Tower, gaining %dMODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT%%% bonus attack speed."

"DOTA_Tooltip_ability_well_tower_spring_forward"				"Spring Forward"
"DOTA_Tooltip_ability_well_tower_spring_forward_Description"	"Increases the target non-support tower's attack speed for a duration."
"DOTA_Tooltip_ability_well_tower_spring_forward_attack_speed"	"%BONUS ATTACK SPEED:"
"DOTA_Tooltip_ability_well_tower_spring_forward_duration"		"DURATION:"

///////////////////////////////
"blacksmith_tower_ability"										"Fire Up"
"blacksmith_tower_ability_desc"									"Increases a non-support tower's attack and ability damage by a percentage for a duration."

"DOTA_Tooltip_modifier_fire_up_1"								"Fired Up"
"DOTA_Tooltip_modifier_fire_up_1_Description"					"Buffed by a Blacksmith Tower, gaining %dMODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE%%% bonus damage."

"DOTA_Tooltip_modifier_fire_up_2"								"Fired Up"
"DOTA_Tooltip_modifier_fire_up_2_Description"					"Buffed by a Blacksmith Tower, gaining %dMODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE%%% bonus damage."

"DOTA_Tooltip_modifier_fire_up_3"								"Fired Up"
"DOTA_Tooltip_modifier_fire_up_3_Description"					"Buffed by a Blacksmith Tower, gaining %dMODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE%%% bonus damage."

"DOTA_Tooltip_ability_blacksmith_tower_fire_up"					"Fire Up"
"DOTA_Tooltip_ability_blacksmith_tower_fire_up_Description"		"Increases the target tower's damage for a duration. The bonus damage applies to abilities as well."
"DOTA_Tooltip_ability_blacksmith_tower_fire_up_damage"			"%BONUS DAMAGE:"
"DOTA_Tooltip_ability_blacksmith_tower_fire_up_duration"		"DURATION:"

///////////////////////////////////
"mushroom_tower_ability"										"Spore"
"mushroom_tower_ability_desc"									"Each attack deals bonus damage based on the percentage of the target's remaining health. For every 1% of health that the target has, the attack deals 1% more damage."

"DOTA_Tooltip_ability_mushroom_tower_spore"						"Spore"
"DOTA_Tooltip_ability_mushroom_tower_spore_Description"			"Each attack deals bonus damage based on the percentage of the target's remaining health. For every 1% of health that the target has, the attack deals 1% more damage."

///////////////////////////////////		
"quark_tower_ability"											"Quantum Beam"
"quark_tower_ability_desc"										"Each consecutive attack on the same unit increases damage. Damage resets upon changing targets."

"DOTA_Tooltip_ability_quark_tower_quantum_beam"					"Quantum Beam"
"DOTA_Tooltip_ability_quark_tower_quantum_beam_Description"		"Each attack on the same unit gains bonus damage. Stacks indefinitely. Damage is reset upon attacking a different unit."
"DOTA_Tooltip_ability_quark_tower_quantum_beam_bonus_damage"	"%BONUS DAMAGE:"

"DOTA_Tooltip_modifier_quantum_beam_indicator"					"Quantum Beam Level"
"DOTA_Tooltip_modifier_quantum_beam_indicator_Description"		"Number of consecutive attacks on the same target."

///////////////////////////////////		
"electricity_tower_ability"										"Arc Lightning"
"electricity_tower_ability_desc"								"Each attack is a chain of lightning that jumps from creep to creep dealing damage."

"DOTA_Tooltip_ability_electricity_tower_arc_lightning_passive"					"Arc Lightning"
"DOTA_Tooltip_ability_electricity_tower_arc_lightning_passive_Description"		"Each attack sends out a chain of lightning that jumps from creep to creep. Each jump deals decreased damage."
"DOTA_Tooltip_ability_electricity_tower_arc_lightning_passive_damage"			"DAMAGE:"
"DOTA_Tooltip_ability_electricity_tower_arc_lightning_passive_damage_decrease"	"%DAMAGE DECREASE PER JUMP:"
"DOTA_Tooltip_ability_electricity_tower_arc_lightning_passive_jump_count"		"JUMPS:"

///////////////////////////////////		
"flame_tower_ability"										"Sunburn"
"flame_tower_ability_desc"									"Each attack applies a burn to the target which casues it to do damage in an AOE around it."

"DOTA_Tooltip_modifier_sunburn"								"Sunburnt"
"DOTA_Tooltip_modifier_sunburn_Description"					"Taking damage over time and burning those around you."

"DOTA_Tooltip_ability_flame_tower_sunburn"					"Sunburn"
"DOTA_Tooltip_ability_flame_tower_sunburn_Description"		"Each attack applies a burn to the target that lasts a short duration. The burn does damage to the target and in an AOE around it each second. The burn stacks."
"DOTA_Tooltip_ability_flame_tower_sunburn_damage"			"DAMAGE:"
"DOTA_Tooltip_ability_flame_tower_sunburn_aoe"				"AOE:"
"DOTA_Tooltip_ability_flame_tower_sunburn_duration"			"DURATION:"

///////////////////////////////////	
"vapor_tower_ability"											"Evaporate"
"vapor_tower_ability_desc"										"Each attack deals damage to creeps near the tower, also creating aftershocks for each creep hit."

"DOTA_Tooltip_ability_vapor_tower_evaporate"					"Evaporate"
"DOTA_Tooltip_ability_vapor_tower_evaporate_Description"		"Each attack deals damage to all creeps near this tower. Each creep hit causes an aftershock to form, dealing damage around it."
"DOTA_Tooltip_ability_vapor_tower_evaporate_damage"				"DAMAGE:"
"DOTA_Tooltip_ability_vapor_tower_evaporate_aftershock_damage"	"AFTERSHOCK DAMAGE:"
"DOTA_Tooltip_ability_vapor_tower_evaporate_aoe"				"INITIAL AOE:"
"DOTA_Tooltip_ability_vapor_tower_evaporate_aftershock_aoe"		"AFTERSHOCK AOE:"

///////////////////////////////////	
"poison_tower_ability"											"Contamination"
"poison_tower_ability_desc"										"Every third attack deals bonus damage."

"DOTA_Tooltip_ability_poison_tower_contamination"				"Contamination"
"DOTA_Tooltip_ability_poison_tower_contamination_Description"	"Every fourth attack deals bonus damage in a 300 Half/150 Full AOE around the target."
"DOTA_Tooltip_ability_poison_tower_contamination_damage_mult"	"%DAMAGE MULTIPLIER:"

///////////////////////////////////	
"life_tower_ability"											"Afterlife"
"life_tower_ability_desc"										"Every few creeps killed by this tower will heal you."

"DOTA_Tooltip_ability_life_tower_afterlife"						"Afterlife"
"DOTA_Tooltip_ability_life_tower_afterlife_Description"			"Every few creeps killed by this tower will heal you. This takes into account all other Life Towers that you own. If you are at or over <font color='0xFFFFFF'>50</font> health it takes <font color='0xFFFFFF'>9</font> kills."
"DOTA_Tooltip_ability_life_tower_afterlife_kills_required"		"KILLS REQUIRED:"
"DOTA_Tooltip_ability_life_tower_afterlife_heal_amount"			"HEAL AMOUNT:"

///////////////////////////////////	
"hydro_tower_ability"											"Desolation"
"hydro_tower_ability_desc"										"This tower shoots slow, non-tracking projectiles that deal splash damage where they land."

"DOTA_Tooltip_ability_hydro_tower_ability"						"Desolation"
"DOTA_Tooltip_ability_hydro_tower_ability_Description"			"Shoots slow non-tracking projectiles that deal splash damage where they land."
"DOTA_Tooltip_ability_hydro_tower_ability_splash_damage"		"DAMAGE:"
"DOTA_Tooltip_ability_hydro_tower_ability_splash_aoe"			"AOE:"

"DOTA_Tooltip_ability_hydro_tower_choose_target"				"Choose Target Point"
"DOTA_Tooltip_ability_hydro_tower_choose_target_Description"	"Choose a point for this tower to attack over and over. This overrides unit targetting."

"DOTA_Tooltip_ability_hydro_tower_reset_target"					"Reset Target Point"
"DOTA_Tooltip_ability_hydro_tower_reset_target_Description"		"Resets the target point, making this tower go back to automatic unit targetting."

///////////////////////////////////	
"trickery_tower_ability"										"Conjure"
"trickery_tower_ability_desc"									"Create a clone of a non-support tower that lasts for a short duration."

"DOTA_Tooltip_modifier_conjure_prevent_cloning"					"Recently Cloned"
"DOTA_Tooltip_modifier_conjure_prevent_cloning_Description"		"This tower has been recently cloned and cannot be cloned again until this debuff ends."
		
"DOTA_Tooltip_modifier_clone"									"Clone"
"DOTA_Tooltip_modifier_clone_Description"						"This is a cloned tower."

"DOTA_Tooltip_ability_trickery_tower_conjure"					"Conjure"
"DOTA_Tooltip_ability_trickery_tower_conjure_Description"		"Creates a clone of the target tower. You cannot upgrade clones and selling them does not return gold. You cannot clone a tower more than once every 60 seconds.\n\nWhen you sell or upgrade a tower that has been recently cloned, you will lose a random clone of that tower type."
"DOTA_Tooltip_ability_trickery_tower_conjure_duration"			"DURATION:"

///////////////////////////////////	
"gunpowder_tower_ability"										"Shrapnade"
"gunpowder_tower_ability_desc"									"Each attack lobs an explosive bomb at a target that does AOE damage on hit. After a short delay, 3 more explosions occur around the target."

"DOTA_Tooltip_ability_gunpowder_tower_shrapnade"				"Shrapnade"
"DOTA_Tooltip_ability_gunpowder_tower_shrapnade_Description"	"Each attack lobs an explosive bomb at a target that does AOE damage on hit. After a short delay, 3 more explosions occur around the target."
"DOTA_Tooltip_ability_gunpowder_tower_shrapnade_damage"			"EXPLOSION DAMAGE:"
"DOTA_Tooltip_ability_gunpowder_tower_shrapnade_splash_aoe"		"EXPLOSION AOE:"

///////////////////////////////
"ice_tower_ability"												"Ice Blast"
"ice_tower_ability_desc"										"Each attack shoots a linear orb that damages creeps it travels through and explodes after travelling a certain distance."

"DOTA_Tooltip_ability_ice_tower_ice_blast"						"Ice Blast"
"DOTA_Tooltip_ability_ice_tower_ice_blast_Description"			"Each attack shoots a linear orb that damages creeps it travels through and explodes after travelling a certain distance. Each creep can be hit twice by the orb, depending on its distance from it. The explosion deals double damage."
"DOTA_Tooltip_ability_ice_tower_ice_blast_damage"				"DAMAGE:"
"DOTA_Tooltip_ability_ice_tower_ice_blast_aoe"					"AOE:"
"DOTA_Tooltip_ability_ice_tower_ice_blast_distance"				"MAX DISTANCE:"

///////////////////////////////////	
"muck_tower_ability"											"Sludge"
"muck_tower_ability_desc"										"Each attack slows creeps in an area around the target creep."

"DOTA_Tooltip_modifier_sludge_slow"								"Slowed"
"DOTA_Tooltip_modifier_sludge_slow_Description"					"Slowed by sludge, losing %dMODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE%%% movement speed." 

"DOTA_Tooltip_ability_muck_tower_sludge_passive"				"Sludge"
"DOTA_Tooltip_ability_muck_tower_sludge_passive_Description"	"Each attack slows creeps in an area around the target creep. Slows lasts a short duration. Slow does not stack."
"DOTA_Tooltip_ability_muck_tower_sludge_passive_duration"		"DURATION:"
"DOTA_Tooltip_ability_muck_tower_sludge_passive_aoe"			"AOE:"
"DOTA_Tooltip_ability_muck_tower_sludge_passive_slow_tooltip"	"%MOVEMENT SLOW:"

///////////////////////////////////	
"gold_tower_ability"											"Arbitrage"
"gold_tower_ability_desc"										"Each creep killed by this tower grants bonus gold."

"DOTA_Tooltip_ability_gold_tower_arbitrage"						"Arbitrage"
"DOTA_Tooltip_ability_gold_tower_arbitrage_Description"			"Each creep killed by this tower grants bonus gold."
"DOTA_Tooltip_ability_gold_tower_arbitrage_bonus_gold"			"%BONUS GOLD:"

///////////////////////////////////	
"windstorm_tower_ability"										"Tornado"
"windstorm_tower_ability_desc"									"Summons a controllable tornado that damages and slows nearby creeps."

"DOTA_Tooltip_ability_windstorm_tower_tornado"					"Tornado"
"DOTA_Tooltip_ability_windstorm_tower_tornado_Description"		"Summons a controllable tornado that damages and slows nearby creeps.\n\nTornado lasts forever but it is destroyed if this tower is sold or upgraded, or if it is moved out of the sector bounds."
"DOTA_Tooltip_ability_windstorm_tower_tornado_damage"			"DAMAGE PER SECOND:"
"DOTA_Tooltip_ability_windstorm_tower_tornado_slow_tooltip"		"%MOVEMENT SLOW:"

"DOTA_Tooltip_ability_windstorm_tornado_slow"					"Windstorm"
"DOTA_Tooltip_ability_windstorm_tornado_slow_Description"		"Slowing and damaging nearby creeps."
"DOTA_Tooltip_ability_windstorm_tornado_slow_damage"			"DAMAGE PER SECOND:"
"DOTA_Tooltip_ability_windstorm_tornado_slow_slow_tooltip"		"%MOVEMENT SLOW:"
"DOTA_Tooltip_ability_windstorm_tornado_slow_radius"			"AOE:"

"DOTA_Tooltip_modifier_tornado_slow"							"Slowed"
"DOTA_Tooltip_modifier_tornado_slow_Description"				"Slowed by a tornado, losing %dMODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE%%% movement speed." 

"DOTA_Tooltip_modifier_tornado_summoned"						"Tornado Summoned"

///////////////////////////////////	
"quake_tower_ability"											"Pulverize"
"quake_tower_ability_desc"										"Each attack has a chance to deal damage in an area around this tower."

"DOTA_Tooltip_ability_quake_tower_pulverize"					"Pulverize"
"DOTA_Tooltip_ability_quake_tower_pulverize_Description"		"Each attack has a chance to deal damage in an area around this tower."
"DOTA_Tooltip_ability_quake_tower_pulverize_damage"				"DAMAGE:"
"DOTA_Tooltip_ability_quake_tower_pulverize_chance"				"%CHANCE:"

///////////////////////////////////	
"enchantment_tower_ability"											"Faerie Fire"
"enchantment_tower_ability_desc"									"An autocast ability that amplifies the damage that creeps take."

"DOTA_Tooltip_ability_enchantment_tower_faerie_fire"				"Faerie Fire"
"DOTA_Tooltip_ability_enchantment_tower_faerie_fire_Description"	"Amplifies the target's damage taken for a short duration."
"DOTA_Tooltip_ability_enchantment_tower_faerie_fire_damage_amp"		"%DAMAGE AMPLIFICATION:"
"DOTA_Tooltip_ability_enchantment_tower_faerie_fire_duration"		"DURATION:"

"DOTA_Tooltip_modifier_faerie_fire"									"Faerie Fire"
"DOTA_Tooltip_modifier_faerie_fire_Description"						"Burned by Faerie Fire, taking bonus damage." 

///////////////////////////////
"flooding_tower_ability"											"Increase/Decrease Splash"
"flooding_tower_ability_desc"										"You can increase or decrease this tower's splash AOE manually. Larger splash means higher BAT and vice versa."

"DOTA_Tooltip_ability_flooding_tower_increase_splash"				"Increase Splash"
"DOTA_Tooltip_ability_flooding_tower_increase_splash_Description"	"Increase this tower's splash AOE. Larger splash means higher BAT."
"DOTA_Tooltip_ability_flooding_tower_increase_splash_splash_aoe"	"FULL DAMAGE AOE:"
"DOTA_Tooltip_ability_flooding_tower_increase_splash_splash_aoe_2"	"HALF DAMAGE AOE:"
"DOTA_Tooltip_ability_flooding_tower_increase_splash_bat"			"BASE ATTACK TIME:"

"DOTA_Tooltip_ability_flooding_tower_decrease_splash"				"Decrease Splash"
"DOTA_Tooltip_ability_flooding_tower_decrease_splash_Description"	"Decrease this tower's splash AOE. Smaller splash means lower BAT."
"DOTA_Tooltip_ability_flooding_tower_decrease_splash_splash_aoe"	"FULL DAMAGE AOE:"
"DOTA_Tooltip_ability_flooding_tower_decrease_splash_splash_aoe_2"	"HALF DAMAGE AOE:"
"DOTA_Tooltip_ability_flooding_tower_decrease_splash_bat"			"BASE ATTACK TIME:"

///////////////////////////////
"laser_tower_ability"											"Laser"
"laser_tower_ability_desc"										"Each attack shoots out a laser at the target, dealing less damage for each other creep around the target."

"DOTA_Tooltip_ability_laser_tower_laser"						"Laser"
"DOTA_Tooltip_ability_laser_tower_laser_Description"			"Each attack shoots out a laser at the target, dealing massive damage. Each creep in a 400 AOE around the target reduces the damage dealt. Minimum damage is 30%%."
"DOTA_Tooltip_ability_laser_tower_laser_damage_reduction"		"%DAMAGE REDUCTION PER CREEP:"

///////////////////////////////
"hail_tower_ability"											"Storm"
"hail_tower_ability_desc"										"Causes this tower to attack multiple creeps at the same time for a short duration."

"DOTA_Tooltip_ability_hail_tower_storm"							"Storm"
"DOTA_Tooltip_ability_hail_tower_storm_Description"				"This tower unleashes a mighty hail storm, temporarily gaining the ability to attack multiple targets at once. Each target takes full damage."
"DOTA_Tooltip_ability_hail_tower_storm_duration"				"DURATION:"
"DOTA_Tooltip_ability_hail_tower_storm_targets"					"MAX TARGETS:"

"DOTA_Tooltip_modifier_storm"									"Storm"
"DOTA_Tooltip_modifier_storm_Description"						"Attacking multiple targets." 

///////////////////////////////
"runic_tower_ability"											"Magic Attack"
"runic_tower_ability_desc"										"Causes this tower to attack all creeps in an area around the main target for a short duration."

"DOTA_Tooltip_ability_runic_tower_magic_attack"					"Magic Attack"
"DOTA_Tooltip_ability_runic_tower_magic_attack_Description"		"Allows this tower to attack all creeps within a 200 AOE of the main target. Splash damage is also dealt around all secondary targets. The bonus attacks deal 50%% damage."
"DOTA_Tooltip_ability_runic_tower_magic_attack_duration"		"DURATION:"

"DOTA_Tooltip_modifier_magic_attack"							"Magic Attack"
"DOTA_Tooltip_modifier_magic_attack_Description"				"Attacking multiple targets." 

///////////////////////////////
"impulse_tower_ability"											"Impetus"
"impulse_tower_ability_desc"									"Attacks do more damage based on distance travelled."

"DOTA_Tooltip_ability_impulse_tower_impetus"					"Impetus"
"DOTA_Tooltip_ability_impulse_tower_impetus_Description"		"Gives strength to attacks, making them deal more damage based on the distance travelled. Damage is calculated as <font color='#FFFFFF'>(Distance/1000)*DamageMultiplier</font>."
"DOTA_Tooltip_ability_impulse_tower_impetus_multiplier"			"DAMAGE MULTIPLIER:"

///////////////////////////////
"obliteration_tower_ability"										"Obliterate"
"obliteration_tower_ability_desc"									"Each attack projectile slows down and gains splash as it travels. Explodes when it hits the target or slows to a top."

"DOTA_Tooltip_ability_obliteration_tower_obliterate"				"Obliterate"
"DOTA_Tooltip_ability_obliteration_tower_obliterate_Description"	"Each attack sends out a projectile that starts with 0 splash. As it travels, the projectile slows down and gains splash. Once the target is hit or the projectile slows to a stop, it explodes, dealing damage in an area equal to the amount of splash gained."
"DOTA_Tooltip_ability_obliteration_tower_obliterate_max_aoe"		"MAX SPLASH:"

///////////////////////////////
"ephemeral_tower_ability"										"Phasing"
"ephemeral_tower_ability_desc"									"Every second of constant attacking lowers base damage slightly. Damage is reset after a few seconds of not attacking or by casting this ability."

"DOTA_Tooltip_ability_ephemeral_tower_phasing"					"Phasing"
"DOTA_Tooltip_ability_ephemeral_tower_phasing_Description"		"Passively, each second of attacking lowers this tower's base damage by a percentage. The damage is reset after 5 seconds of not attacking or by casting this ability."
"DOTA_Tooltip_ability_ephemeral_tower_phasing_damage_reduction"	"%DAMAGE REDUCTION PER SECOND:"
"DOTA_Tooltip_ability_ephemeral_tower_phasing_max_reduction"	"%MAX DAMAGE REDUCTION:"

///////////////////////////////
"flamethrower_tower_ability"									"Naplam"
"flamethrower_tower_ability_desc"								"Each attack adds a stack of Napalm to creeps in an area around the target. Upon death, a Napalmed creep does damage in an area around it for each stack of napalm."

"DOTA_Tooltip_ability_flamethrower_tower_napalm"				"Napalm"
"DOTA_Tooltip_ability_flamethrower_tower_napalm_Description"	"Each attack adds a stack of Napalm to creeps in an area around the target. Napalm stacks lasts forever and can stack indefinately. Upon death, a Napalmed creep does damage in an area around it for each stack of Napalm on it."
"DOTA_Tooltip_ability_flamethrower_tower_napalm_damage"			"DAMAGE PER STACK:"
"DOTA_Tooltip_ability_flamethrower_tower_napalm_aoe"			"AOE:"

"DOTA_Tooltip_modifier_napalm"									"Napalm"
"DOTA_Tooltip_modifier_napalm_Description"						"" 

///////////////////////////////
"haste_tower_ability"											"Wrath"
"haste_tower_ability_desc"										"Each attack increases attack speed. Stacks up to 17 times. Resets after 4 seconds of not attacking."

"DOTA_Tooltip_ability_haste_tower_wrath"						"Wrath"
"DOTA_Tooltip_ability_haste_tower_wrath_Description"			"Each attack adds a stack of Wrath to this tower. Each stack increases attack speed. The stacks get reset after 4 seconds of not attacking."
"DOTA_Tooltip_ability_haste_tower_wrath_attack_speed"			"%ATTACK SPEED PER STACK:"
"DOTA_Tooltip_ability_haste_tower_wrath_cap"					"MAX STACKS:"

"DOTA_Tooltip_modifier_wrath_reset"								"Wrath Reset"
"DOTA_Tooltip_modifier_wrath_reset_Description"					"Wrath stacks get removed after 4 seconds of not attacking." 

"DOTA_Tooltip_modifier_wrath_indicator"							"Wrath"

///////////////////////////////
"torrent_tower_ability"											"Douse"
"torrent_tower_ability_desc"									"Every 10 attacks level up this ability. Upon casting, this ability does damage to all creeps near this tower based on this ability's level. Levels is reset to 0 after casting."

"DOTA_Tooltip_ability_torrent_tower_douse_1"					"Douse"
"DOTA_Tooltip_ability_torrent_tower_douse_1_Description"		"This ability levels up every 10 attacks. Upon casting, damage is dealt to all creeps near this tower based on this ability's level. Level gets reset to 0 after casting."
"DOTA_Tooltip_ability_torrent_tower_douse_1_damage"				"DAMAGE:"
"DOTA_Tooltip_ability_torrent_tower_douse_1_aoe"				"AOE:"

"DOTA_Tooltip_ability_torrent_tower_douse_2"					"Douse"
"DOTA_Tooltip_ability_torrent_tower_douse_2_Description"		"This ability levels up every 10 attacks. Upon casting, damage is dealt to all creeps near this tower based on this ability's level. Level gets reset to 0 after casting."
"DOTA_Tooltip_ability_torrent_tower_douse_2_damage"				"DAMAGE:"
"DOTA_Tooltip_ability_torrent_tower_douse_2_aoe"				"AOE:"

"DOTA_Tooltip_modifier_douse_passive"							"Douse Level"

///////////////////////////////
"nova_tower_ability"											"Explode"
"nova_tower_ability_desc"										"This tower explodes with each attack, dealing damage and slowing all creeps around it."

"DOTA_Tooltip_ability_nova_tower_explode"						"Explode"
"DOTA_Tooltip_ability_nova_tower_explode_Description"			"This tower explodes with each attack, dealing damage and slowing all creeps around it. Slow lasts 3 seconds."
"DOTA_Tooltip_ability_nova_tower_explode_damage"				"DAMAGE:"
"DOTA_Tooltip_ability_nova_tower_explode_aoe"					"AOE:"
"DOTA_Tooltip_ability_nova_tower_explode_slow_tooltip"			"%SLOW:"

"DOTA_Tooltip_modifier_explode_slow"							"Slowed"
"DOTA_Tooltip_modifier_wrath_reset_Description"					"Slowed by a Nova tower, losing %dMODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE%%% movement speed." 

///////////////////////////////
"erosion_tower_ability"											"Acid Attack"
"erosion_tower_ability_desc"									"Each attack applies a DoT debuff to all creeps around the target and amplifies the damage they take."

"DOTA_Tooltip_ability_erosion_tower_acid_attack"				"Acid Attack"
"DOTA_Tooltip_ability_erosion_tower_acid_attack_Description"	"Each attack applies a DoT debuff to all creeps within a 400 AOE around the target, as well as increasing the damage they take. The DoT debuff stacks but the the damage amplification doesn't."
"DOTA_Tooltip_ability_erosion_tower_acid_attack_damage_amp"		"%DAMAGE AMPLIFICATION:"
"DOTA_Tooltip_ability_erosion_tower_acid_attack_dot"			"DAMAGE PER SECOND:"
"DOTA_Tooltip_ability_erosion_tower_acid_attack_duration"		"DURATION:"

"DOTA_Tooltip_modifier_acid_attack_dot"							"Eroded"
"DOTA_Tooltip_modifier_acid_attack_dot_Description"				"Taking damage every second." 

"DOTA_Tooltip_modifier_acid_attack_damage_amp"					"Eroded"
"DOTA_Tooltip_modifier_acid_attack_damage_amp_Description"		"Taking bonus damage." 

///////////////////////////////
"polar_tower_ability"											"Frostbite"
"polar_tower_ability_desc"										"Autocast ability that temporarily burns away a portion of the target's current health. The target regains the health lost at the end of the duration minus a percentage of the damage taken while Frostbitten."

"DOTA_Tooltip_ability_polar_tower_frostbite"					"Frostbite"
"DOTA_Tooltip_ability_polar_tower_frostbite_Description"		"Temporarily burns away a portion of the target's current health. The target regains the health lost at the end of the duration minus a percentage of the damage taken while Frostbitten.\nA Frostbitten creep cannot be targeted again until the debuff wears off."
"DOTA_Tooltip_ability_polar_tower_frostbite_health_burn"		"%HEALTH BURN:"
"DOTA_Tooltip_ability_polar_tower_frostbite_damage_taken_pcnt"	"%DAMAGE TAKEN PERCENT:"
"DOTA_Tooltip_ability_polar_tower_frostbite_duration"			"DURATION:"

"DOTA_Tooltip_modifier_polar_frostbite"							"Frostbitten"
"DOTA_Tooltip_modifier_polar_frostbite_Description"				"Regaining health lost at the end of the duration." 

"polar_tower_frostbite_error"									"That creep is already Frostbitten!"

//////////////////////////////
"jinx_tower_ability"											"Maledict"
"jinx_tower_ability_desc"										"Each attack applies Maledict to creeps near the target."

"DOTA_Tooltip_ability_jinx_tower_maledict"						"Maledict"
"DOTA_Tooltip_ability_jinx_tower_maledict_Description"			"Each attack curses creeps near the target with Maledict. Maledicted creeps tick every few seconds, taking damage equal to a percentage of the damage taken since the curse began."
"DOTA_Tooltip_ability_jinx_tower_maledict_tick_interval"		"INTERVAL:"
"DOTA_Tooltip_ability_jinx_tower_maledict_ticks"				"TICKS:"
"DOTA_Tooltip_ability_jinx_tower_maledict_damage_taken"			"DAMAGE TAKEN TO DAMAGE:"
"DOTA_Tooltip_ability_jinx_tower_maledict_aoe"					"AOE:"

"DOTA_Tooltip_modifier_jinx_maledict"							"Maledicted"
"DOTA_Tooltip_modifier_jinx_maledict_Description"				"Taking damage every few seconds based on the damage taken since Maledict began." 

//////////////////////////////
"roots_tower_ability"											"Gaia's Wrath"
"roots_tower_ability_desc"										"Each attack applies a slow and a DoT debuff to all creeps in a line in the direction of the main target."

"DOTA_Tooltip_ability_roots_tower_gaias_wrath"					"Gaia's Wrath"
"DOTA_Tooltip_ability_roots_tower_gaias_wrath_Description"		"Each attack sends out a line of with 300 that slows creeps hit as well as adding a damage over time debuff to it. Slow does not stack but damage does."
"DOTA_Tooltip_ability_roots_tower_gaias_wrath_slow_tooltip"		"%MOVEMENT SLOW:"
"DOTA_Tooltip_ability_roots_tower_gaias_wrath_dps"				"DAMAGE PER SECOND:"
"DOTA_Tooltip_ability_roots_tower_gaias_wrath_duration"			"DURATION:"

"DOTA_Tooltip_modifier_gaias_wrath_slow"						"Slowed"
"DOTA_Tooltip_modifier_gaias_wrath_damage"						"Damage Over Time"



//===================//
//====HUD Strings====//
//===================//

"etd_lumber_title"	"Lumber"

"etd_water"		"Water"
"etd_fire"		"Fire"
"etd_nature"	"Nature"
"etd_earth"		"Earth"
"etd_light"		"Light"
"etd_dark"		"Dark"

"element_mode_ap"			"All Pick"
"element_mode_ap_desc"		"Everyone can pick and choose which elementals they want to summon."
"element_mode_ar"			"All Random"
"element_mode_ar_desc"		"Everyone gets their elemental choices selected randomly."
"element_mode_sr"			"Same Random"
"element_mode_sr_desc"		"Everyone is given the same random elemental choices."

"creep_order_chaos"			"Chaos"
"creep_order_chaos_desc"	"Waves are in random order. The first 5 waves do not change."
"creep_order_normal"		"Normal"
"creep_order_normal_desc"	"Waves are in standard order."

"gamemode_competitive"		"Competitive"
"gamemode_competitive_desc"	"Game is not mixed difficulty. For pros only."
"gamemode_casual"			"Casual"
"gamemode_casual_desc"		"Everyone plays on their own difficulty."
"gamemode_race"				"Race"
"gamemode_race_desc"		"???"

"difficulty_very_easy"		"Very Easy"
"difficulty_easy"			"Easy"
"difficulty_normal"			"Normal"
"difficulty_hard"			"Hard"
"difficulty_very_hard"		"Very Hard"
"difficulty_insane"			"Insane"

"game_length_normal"		"Normal"
"game_length_short"			"Short"
"game_length_very_short"	"Very Short"
"game_length_developer"		"Developer"