"towers" 
{
    //===============================================================================================
    // Basic Arrow Tower //==========================================================================
    //===============================================================================================
    "basic_arrow_tower"
    {
        "Level"                     "1"
        "Cost"                      "7"
        "TotalCost"                 "7"
        "Element"                   "none"
        "Damage"                    "3"
        "DamageType"                "composite"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Support"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/arrow_tower/tower.vmdl"
        "ModelScale"                "0.575"

        "BuildTime"                 "1"

        "Upgrades"
        {
            "Count"     "1"
            "1"         "advanced_arrow_tower"
        }
    }

    //===============================================================================================
    // Advanced Arrow Tower //=======================================================================
    //===============================================================================================
    "advanced_arrow_tower"
    {
        "Level"                     "2"
        "Cost"                      "13"
        "TotalCost"                 "20"
        "Element"                   "none"
        "Damage"                    "9"
        "DamageType"                "composite"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Support"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/arrow_tower/tower.vmdl"
        "ModelScale"                "0.625"

        "BuildTime"                 "1"

        "Upgrades"
        {
            "Count"     "1"
            "1"         "super_arrow_tower"
        }
    }

    //===============================================================================================
    // Super Arrow Tower //=======================================================================
    //===============================================================================================
    "super_arrow_tower"
    {
        "Level"                     "3"
        "Cost"                      "37"
        "TotalCost"                 "57"
        "Element"                   "none"
        "Damage"                    "27"
        "DamageType"                "composite"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Support"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/arrow_tower/tower.vmdl"
        "ModelScale"                "0.675"

        "BuildTime"                 "1"

        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Basic Cannon Tower //=========================================================================
    //===============================================================================================
    "basic_cannon_tower"
    {
        "Level"                     "1"
        "Cost"                      "7"
        "TotalCost"                 "7"
        "Element"                   "none"
        "Damage"                    "3"
        "DamageType"                "composite"
        "AOE_Full"                  "125"
        "AOE_Half"                  "250"

        "ScriptClass"               "CannonTower"
        "TowerType"                 "Support"
        
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "1.5"
        "particle_folder"           "particles/units/heroes/hero_jakiro"
        "ProjectileModel"           "particles/units/heroes/hero_jakiro/jakiro_base_attack_fire.vpcf"
        "ProjectileSpeed"           "800"

        "Model"                     "models/cannon_tower/cannon_tower.vmdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "1"

        "Upgrades"
        {
            "Count"     "1"
            "1"         "advanced_cannon_tower"
        }
    }

    //===============================================================================================
    // Advanced Cannon Tower //=========================================================================
    //===============================================================================================
    "advanced_cannon_tower"
    {
        "Level"                     "2"
        "Cost"                      "13"
        "TotalCost"                 "20"
        "Element"                   "none"
        "Damage"                    "9"
        "DamageType"                "composite"
        "AOE_Full"                  "125"
        "AOE_Half"                  "250"

        "ScriptClass"               "CannonTower"
        "TowerType"                 "Support"
        
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "1.5"
        "particle_folder"           "particles/units/heroes/hero_jakiro"
        "ProjectileModel"           "particles/units/heroes/hero_jakiro/jakiro_base_attack_fire.vpcf"
        "ProjectileSpeed"           "800"

        "Model"                     "models/cannon_tower/cannon_tower.vmdl"
        "ModelScale"                "1"
        "BuildTime"                 "1"

        "Upgrades"
        {
            "Count"     "1"
            "1"         "super_cannon_tower"
        }
    }

    //===============================================================================================
    // Super Cannon Tower //=========================================================================
    //===============================================================================================
    "super_cannon_tower"
    {
        "Level"                     "3"
        "Cost"                      "37"
        "TotalCost"                 "57"
        "Element"                   "none"
        "Damage"                    "27"
        "DamageType"                "composite"
        "AOE_Full"                  "125"
        "AOE_Half"                  "250"

        "ScriptClass"               "CannonTower"
        "TowerType"                 "Support"
        
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "1.5"
        "particle_folder"           "particles/units/heroes/hero_jakiro"
        "ProjectileModel"           "particles/units/heroes/hero_jakiro/jakiro_base_attack_fire.vpcf"
        "ProjectileSpeed"           "800"

        "Model"                     "models/cannon_tower/cannon_tower.vmdl"
        "ModelScale"                "1.1"
        "BuildTime"                 "1"

        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Water Tower //================================================================================
    //===============================================================================================
    "water_tower"
    {
        "Level"                     "1"
        "Cost"                      "175"
        "TotalCost"                 "175"
        "Element"                   "water"
        "Damage"                    "54"
        "DamageType"                "water"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "water" "1"
        }
        "Upgrades"
        {
            "Count"     "6"
            "1"         "focused_water_tower"
            "2"         "vapor_tower"
            "3"         "well_tower"
            "4"         "hydro_tower"
            "5"         "ice_tower"
            "6"         "poison_tower"
        }
    }

    //===============================================================================================
    // Focused Water Tower //======================================================================
    //===============================================================================================
    "focused_water_tower"
    {
        "Level"                     "2"
        "Cost"                      "450"
        "TotalCost"                 "625"
        "Element"                   "water"
        "Damage"                    "270"
        "DamageType"                "water"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "2"

        "Requirements"
        {
            "water" "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "refined_water_tower"
        }
    }

    //===============================================================================================
    // Refined Water Tower //======================================================================
    //===============================================================================================
    "refined_water_tower"
    {
        "Level"                     "3"
        "Cost"                      "1300"
        "TotalCost"                 "1925"
        "Element"                   "water"
        "Damage"                    "1350"
        "DamageType"                "water"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"

        "Requirements"
        {
            "water" "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Pure Water Tower //===========================================================================
    //===============================================================================================
    "pure_water_tower"
    {
        "Level"                     "4"
        "Cost"                      "9075"
        "TotalCost"                 "11000"
        "Element"                   "water"
        "Damage"                    "20250"
        "DamageType"                "water"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1.1"
        "BuildTime"                 "2"

        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Fire Tower //=================================================================================
    //===============================================================================================
    "fire_tower"
    {
        "Level"                     "1"
        "Cost"                      "175"
        "TotalCost"                 "175"
        "Element"                   "fire"
        "Damage"                    "21"
        "DamageType"                "fire"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"

        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "2"

        "Requirements"
        {
            "fire"  "1"
        }
        "Upgrades"
        {
            "Count"     "6"
            "1"         "focused_fire_tower"
            "2"         "vapor_tower"
            "3"         "flame_tower"
            "4"         "blacksmith_tower"
            "5"         "electricity_tower"
            "6"         "magic_tower"
        }
    }

    //===============================================================================================
    // Focused Fire Tower //======================================================================
    //===============================================================================================
    "focused_fire_tower"
    {
        "Level"                     "2"
        "Cost"                      "450"
        "TotalCost"                 "625"
        "Element"                   "fire"
        "Damage"                    "105"
        "DamageType"                "fire"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"

        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "fire"  "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "refined_fire_tower"
        }
    }

    //===============================================================================================
    // Refined Fire Tower //=========================================================================
    //===============================================================================================
    "refined_fire_tower"
    {
        "Level"                     "3"
        "Cost"                      "1300"
        "TotalCost"                 "1925"
        "Element"                   "fire"
        "Damage"                    "525"
        "DamageType"                "fire"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"

        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "fire"  "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Pure Fire Tower //============================================================================
    //===============================================================================================
    "pure_fire_tower"
    {
        "Level"                     "4"
        "Cost"                      "9075"
        "TotalCost"                 "11000"
        "Element"                   "fire"
        "Damage"                    "7875"
        "DamageType"                "fire"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"

        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        

        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Nature Tower //===============================================================================
    //===============================================================================================
    "nature_tower"
    {
        "Level"                     "1"
        "Cost"                      "175"
        "TotalCost"                 "175"
        "Element"                   "nature"
        "Damage"                    "126"
        "DamageType"                "nature"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_rubick/rubick_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_rubick"
        "ProjectileSpeed"           "1500"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "6"
            "1"         "focused_nature_tower"
            "2"         "well_tower"
            "3"         "flame_tower"
            "4"         "mushroom_tower"
            "5"         "life_tower"
            "6"         "disease_tower"
        }
    }

    //===============================================================================================
    // Focused Nature Tower //=======================================================================
    //===============================================================================================
    "focused_nature_tower"
    {
        "Level"                     "2"
        "Cost"                      "450"
        "TotalCost"                 "625"
        "Element"                   "nature"
        "Damage"                    "630"
        "DamageType"                "nature"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_rubick/rubick_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_rubick"
        "ProjectileSpeed"           "1500"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "nature"    "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "refined_nature_tower"
        }
    }

    //===============================================================================================
    // Refined Nature Tower //=====================================================================
    //===============================================================================================
    "refined_nature_tower"
    {
        "Level"                     "3"
        "Cost"                      "1300"
        "TotalCost"                 "1925"
        "Element"                   "nature"
        "Damage"                    "3150"
        "DamageType"                "nature"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_rubick/rubick_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_rubick"
        "ProjectileSpeed"           "1500"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "nature"    "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Pure Nature Tower //=====================================================================
    //===============================================================================================
    "pure_nature_tower"
    {
        "Level"                     "4"
        "Cost"                      "9075"
        "TotalCost"                 "11000"
        "Element"                   "nature"
        "Damage"                    "47250"
        "DamageType"                "nature"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"

        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_rubick/rubick_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_rubick"
        "ProjectileSpeed"           "1500"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        

        "Upgrades"
        {
        }
    }


    //===============================================================================================
    // Earth Tower //================================================================================
    //===============================================================================================
    "earth_tower"
    {
        "Level"                     "1"
        "Cost"                      "175"
        "TotalCost"                 "175"
        "Element"                   "earth"
        "Damage"                    "50"
        "DamageType"                "earth"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "earth" "1"
        }
        "Upgrades"
        {
            "Count"     "6"
            "1"         "focused_earth_tower"
            "2"         "hydro_tower"
            "3"         "blacksmith_tower"
            "4"         "mushroom_tower"
            "5"         "quark_tower"
            "6"         "gunpowder_tower"
        }
    }

    //===============================================================================================
    // Focused Earth Tower //======================================================================
    //===============================================================================================
    "focused_earth_tower"
    {
        "Level"                     "2"
        "Cost"                      "450"
        "TotalCost"                 "625"
        "Element"                   "earth"
        "Damage"                    "250"
        "DamageType"                "earth"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "earth" "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "refined_earth_tower"
        }
    }

    //===============================================================================================
    // Refined Earth Tower //======================================================================
    //===============================================================================================
    "refined_earth_tower"
    {
        "Level"                     "3"
        "Cost"                      "1300"
        "TotalCost"                 "1925"
        "Element"                   "earth"
        "Damage"                    "1250"
        "DamageType"                "earth"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "earth" "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Pure Earth Tower //===========================================================================
    //===============================================================================================
    "pure_earth_tower"
    {
        "Level"                     "4"
        "Cost"                      "9075"
        "TotalCost"                 "11000"
        "Element"                   "earth"
        "Damage"                    "18750"
        "DamageType"                "earth"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"

        "ScriptClass"               "BasicTowerAOE"
        "TowerType"                 "Normal"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1.1"
        "BuildTime"                 "2"
        

        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Light Tower //================================================================================
    //===============================================================================================
    "light_tower"
    {
        "Level"                     "1"
        "Cost"                      "175"
        "TotalCost"                 "175"
        "Element"                   "light"
        "Damage"                    "126"
        "DamageType"                "light"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "2000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "light" "1"
        }
        "Upgrades"
        {
            "Count"     "6"
            "1"         "focused_light_tower"
            "2"         "ice_tower"
            "3"         "electricity_tower"
            "4"         "life_tower"
            "5"         "quark_tower"
            "6"         "trickery_tower"
        }
    }

    //===============================================================================================
    // Focused Light Tower //========================================================================
    //===============================================================================================
    "focused_light_tower"
    {
        "Level"                     "2"
        "Cost"                      "450"
        "TotalCost"                 "625"
        "Element"                   "light"
        "Damage"                    "630"
        "DamageType"                "light"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "light" "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "refined_light_tower"
        }
    }

    //===============================================================================================
    // Refined Light Tower //========================================================================
    //===============================================================================================
    "refined_light_tower"
    {
        "Level"                     "3"
        "Cost"                      "1300"
        "TotalCost"                 "1925"
        "Element"                   "light"
        "Damage"                    "3150"
        "DamageType"                "light"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "light" "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Pure Light Tower //===========================================================================
    //===============================================================================================
    "pure_light_tower"
    {
        "Level"                     "4"
        "Cost"                      "9075"
        "TotalCost"                 "11000"
        "Element"                   "light"
        "Damage"                    "47250"
        "DamageType"                "light"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"

        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1.1"
        "BuildTime"                 "2"
        
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Dark Tower //=================================================================================
    //===============================================================================================
    "dark_tower"
    {
        "Level"                     "1"
        "Cost"                      "175"
        "TotalCost"                 "175"
        "Element"                   "dark"
        "Damage"                    "240"
        "DamageType"                "dark"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"

        "AttackRate"                "1.5"
        "ProjectileModel"           "particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_shadow_demon"  
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "dark"  "1"
        }
        "Upgrades"
        {
            "Count"     "6"
            "1"         "focused_dark_tower"
            "2"         "poison_tower"
            "3"         "magic_tower"
            "4"         "disease_tower"
            "5"         "gunpowder_tower"
            "6"         "trickery_tower"
        }
    }

    //===============================================================================================
    // Focused Dark Tower //=========================================================================
    //===============================================================================================
    "focused_dark_tower"
    {
        "Level"                     "2"
        "Cost"                      "450"
        "TotalCost"                 "625"
        "Element"                   "dark"
        "Damage"                    "1200"
        "DamageType"                "dark"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"

        "AttackRate"                "1.5"
        "ProjectileModel"           "particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_shadow_demon"  
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "dark"  "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "refined_dark_tower"
        }
    }


    //===============================================================================================
    // Refined Dark Tower //=========================================================================
    //===============================================================================================
    "refined_dark_tower"
    {
        "Level"                     "3"
        "Cost"                      "1300"
        "TotalCost"                 "1925"
        "Element"                   "dark"
        "Damage"                    "6000"
        "DamageType"                "dark"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"

        "AttackRate"                "1.5"
        "ProjectileModel"           "particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_shadow_demon"  
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1"
        "BuildTime"                 "2"
        
        "Requirements"
        {
            "dark"  "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Pure Dark Tower //============================================================================
    //===============================================================================================
    "pure_dark_tower"
    {
        "Level"                     "4"
        "Cost"                      "9075"
        "TotalCost"                 "11000"
        "Element"                   "dark"
        "Damage"                    "90000"
        "DamageType"                "dark"

        "ScriptClass"               "BasicTower"
        "TowerType"                 "Normal"

        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"

        "AttackRate"                "1.5"
        "ProjectileModel"           "particles/units/heroes/hero_shadow_demon/shadow_demon_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_shadow_demon"  
        "ProjectileSpeed"           "1000"

        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1.1"
        "BuildTime"                 "2"

        "Upgrades"
        {
        }
    }


    //===============================================================================================
    //===============================================================================================
    // Dual Towers //================================================================================
    //===============================================================================================
    //===============================================================================================

    //===============================================================================================
    // Magic Tower Level 1//=========================================================================
    //===============================================================================================
    "magic_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
        }                   
        "Damage"                    "600"
        "DamageType"                "dark"
        "ScriptClass"               "MagicTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "1350"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_invoker"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "towers/magic_tower"
        "BuildTime"                 "3"

        "Requirements"
        {
            "dark"  "1"
            "fire"  "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "magic_tower_2"
            "2"         "runic_tower"
            "3"         "flamethrower_tower"
            "4"         "jinx_tower"
            "5"         "erosion_tower"
        }
    }


    //===============================================================================================
    // Magic Tower Level 2//=========================================================================
    //===============================================================================================
    "magic_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
        }                   
        "Damage"                    "3000"
        "DamageType"                "dark"
        "ScriptClass"               "MagicTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "1350"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_invoker"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.95"
        "UpgradeIcon"               "towers/magic_tower"
        "BuildTime"                 "3"


        "Requirements"
        {
            "dark"  "2"
            "fire"  "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "magic_tower_3"
        }
    }

    //===============================================================================================
    // Magic Tower Level 3//=========================================================================
    //===============================================================================================
    "magic_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"

        "Element"
        {
            "1"     "dark"
            "2"     "fire"
        }                   
        "Damage"                    "15000"
        "DamageType"                "dark"
        "ScriptClass"               "MagicTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "1350"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_invoker"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "1.05"
        "UpgradeIcon"               "towers/magic_tower"
        "BuildTime"                 "3"

        
        "Requirements"
        {
            "dark"  "3"
            "fire"  "3"
        }
        "Upgrades"
        {
        }
    }


    //===============================================================================================
    // Disease Tower Level 1 //======================================================================
    //===============================================================================================
    "disease_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "dark"
            "2"     "nature"
        }                   
        "Damage"                    "66"
        "DamageType"                "dark"
        "ScriptClass"               "DiseaseTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_bane"
        "ProjectileModel"           "particles/units/heroes/hero_bane/bane_projectile.vpcf"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/heroes/undying/undying_tower.mdl"
        "ModelScale"                "0.6"
        "UpgradeIcon"               "towers/disease_tower_soul_reaper"
        "BuildTime"                 "3"


        "Requirements"
        {
            "dark"      "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "disease_tower_2"
            "2"         "flooding_tower"
            "3"         "obliteration_tower"
            "4"         "roots_tower"
            "5"         "jinx_tower"
        }
    }

    //===============================================================================================
    // Disease Tower Level 2 //======================================================================
    //===============================================================================================
    "disease_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "dark"
            "2"     "nature"
        }                   
        "Damage"                    "330"
        "DamageType"                "dark"
        "ScriptClass"               "DiseaseTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_bane"
        "ProjectileModel"           "particles/units/heroes/hero_bane/bane_projectile.vpcf"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/heroes/undying/undying_tower.mdl"
        "ModelScale"                "0.7"
        "UpgradeIcon"               "towers/disease_tower_soul_reaper"
        "BuildTime"                 "3"


        "Requirements"
        {
            "dark"      "2"
            "nature"    "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "disease_tower_3"
        }
    }

    //===============================================================================================
    // Disease Tower Level 3 //======================================================================
    //===============================================================================================
    "disease_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "dark"
            "2"     "nature"
        }                   
        "Damage"                    "1650"
        "DamageType"                "dark"
        "ScriptClass"               "DiseaseTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_bane"
        "ProjectileModel"           "particles/units/heroes/hero_bane/bane_projectile.vpcf"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/heroes/undying/undying_tower.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/disease_tower_soul_reaper"
        "BuildTime"                 "3"

        
        "Requirements"
        {
            "dark"      "3"
            "nature"    "3"
        }
        "Upgrades"
        {
        }
    }


    //===============================================================================================
    // Well Tower Level 1 //=========================================================================
    //===============================================================================================
    "well_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "nature"
            "2"     "water"
        }                   
        "Damage"                    "210"
        "DamageType"                "water"
        "ScriptClass"               "WellTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "800"
        "Model"                     "models/well/well.vmdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "morphling_waveform"
        "BuildTime"                 "3"


        "Requirements"
        {
            "water"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "well_tower_2"
            "2"         "flooding_tower"
            "3"         "impulse_tower"
            "4"         "ephemeral_tower"
            "5"         "torrent_tower"
        }
    }

    //===============================================================================================
    // Well Tower Level 2 //=========================================================================
    //===============================================================================================
    "well_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "nature"
            "2"     "water"
        }                   
        "Damage"                    "1050"
        "DamageType"                "water"
        "ScriptClass"               "WellTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "800"
        "Model"                     "models/well/well.vmdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "morphling_waveform"
        "BuildTime"                 "3"


        "Requirements"
        {
            "water"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "well_tower_3"
        }
    }

    //===============================================================================================
    // Well Tower Level 3 //=========================================================================
    //===============================================================================================
    "well_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "nature"
            "2"     "water"
        }                   
        "Damage"                    "5250"
        "DamageType"                "water"
        "ScriptClass"               "WellTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "800"
        "Model"                     "models/well/well.vmdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "morphling_waveform"
        "BuildTime"                 "3"


        "Requirements"
        {
            "water"     "3"
            "nature"    "3"
        }
        "Upgrades"
        {
        }
    }


    //===============================================================================================
    // Blacksmith Tower Level 1 //===================================================================
    //===============================================================================================
    "blacksmith_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
        }                   
        "Damage"                    "210"
        "DamageType"                "fire"
        "ScriptClass"               "BlacksmithTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/bad_column001.mdl"
        "ModelScale"                "0.6"
        "UpgradeIcon"               "towers/blacksmith_tower_fire_up"
        "BuildTime"                 "3"


        "Requirements"
        {
            "fire"      "1"
            "earth"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "blacksmith_tower_2"
            "2"         "gold_tower"
            "3"         "quake_tower"
            "4"         "haste_tower"
            "5"         "flamethrower_tower"
        }
    }

    //===============================================================================================
    // Blacksmith Tower Level 2 //===================================================================
    //===============================================================================================
    "blacksmith_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
        }                   
        "Damage"                    "1050"
        "DamageType"                "fire"
        "ScriptClass"               "BlacksmithTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/bad_column001.mdl"
        "ModelScale"                "0.7"
        "UpgradeIcon"               "towers/blacksmith_tower_fire_up"
        "BuildTime"                 "3"


        "Requirements"
        {
            "fire"      "2"
            "earth"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "blacksmith_tower_3"
        }
    }

    //===============================================================================================
    // Blacksmith Tower Level 3 //===================================================================
    //===============================================================================================
    "blacksmith_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
        }                   
        "Damage"                    "5250"
        "DamageType"                "fire"
        "ScriptClass"               "BlacksmithTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_lina"
        "ProjectileModel"           "particles/units/heroes/hero_lina/lina_base_attack.vpcf"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/bad_column001.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/blacksmith_tower_fire_up"
        "BuildTime"                 "3"


        "Requirements"
        {
            "fire"      "3"
            "earth"     "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Mushroom Tower Level 1 //=====================================================================
    //===============================================================================================
    "mushroom_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "earth"
            "2"     "nature"
        }
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"                   
        "Damage"                    "100"
        "DamageType"                "earth"
        "ScriptClass"               "MushroomTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/undying/undying_tower.mdl"
        "ModelScale"                "0.6"
        "UpgradeIcon"               "brewmaster_earth_pulverize"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "mushroom_tower_2"
            "2"         "quake_tower"
            "3"         "enchantment_tower"
            "4"         "ephemeral_tower"
            "5"         "roots_tower"
        }
    }

    //===============================================================================================
    // Mushroom Tower Level 2 //=====================================================================
    //===============================================================================================
    "mushroom_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "earth"
            "2"     "nature"
        }
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"                   
        "Damage"                    "500"
        "DamageType"                "earth"
        "ScriptClass"               "MushroomTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/undying/undying_tower.mdl"
        "ModelScale"                "0.7"
        "UpgradeIcon"               "brewmaster_earth_pulverize"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "mushroom_tower_3"
        }
    }

    //===============================================================================================
    // Mushroom Tower Level 3 //=====================================================================
    //===============================================================================================
    "mushroom_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "earth"
            "2"     "nature"
        }
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"                   
        "Damage"                    "2500"
        "DamageType"                "earth"
        "ScriptClass"               "MushroomTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/undying/undying_tower.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "brewmaster_earth_pulverize"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "3"
            "nature"    "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Quark Tower Level 1 //========================================================================
    //===============================================================================================
    "quark_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "earth"
            "2"     "light"
        }               
        "Damage"                    "350"
        "DamageType"                "light"
        "ScriptClass"               "QuarkTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "2000"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.6"
        "UpgradeIcon"               "towers/quark_tower_quantum_beam"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "quark_tower_2"
            "2"         "gold_tower"
            "3"         "laser_tower"
            "4"         "enchantment_tower"
            "5"         "polar_tower"
        }
    }

    //===============================================================================================
    // Quark Tower Level 2 //========================================================================
    //===============================================================================================
    "quark_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "earth"
            "2"     "light"
        }               
        "Damage"                    "1750"
        "DamageType"                "light"
        "ScriptClass"               "QuarkTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.7"
        "UpgradeIcon"               "towers/quark_tower_quantum_beam"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "2"
            "light"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "quark_tower_3"
        }
    }

    //===============================================================================================
    // Quark Tower Level 3 //========================================================================
    //===============================================================================================
    "quark_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "earth"
            "2"     "light"
        }               
        "Damage"                    "8750"
        "DamageType"                "light"
        "ScriptClass"               "QuarkTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/quark_tower_quantum_beam"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "3"
            "light"     "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Electricity Tower Level 1 //==================================================================
    //===============================================================================================
    "electricity_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "fire"
            "2"     "light"
        }               
        "Damage"                    "0"
        "DamageType"                "fire"
        "ScriptClass"               "ElectricityTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1500"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "1000"
        "Model"                     "models/fof_psychonic_prop/fof_psychonic_prop.vmdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/electricty_tower_conjure_lightning"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "electricity_tower_2"
            "2"         "gold_tower"
            "3"         "windstorm_tower"
            "4"         "runic_tower"
            "5"         "nova_tower"
        }
    }

    //===============================================================================================
    // Electricity Tower Level 2 //==================================================================
    //===============================================================================================
    "electricity_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "fire"
            "2"     "light"
        }               
        "Damage"                    "0"
        "DamageType"                "fire"
        "ScriptClass"               "ElectricityTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1100"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "1000"
        "Model"                     "models/fof_psychonic_prop/fof_psychonic_prop.vmdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "towers/electricty_tower_conjure_lightning"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "2"
            "light"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "electricity_tower_3"
        }
    }

    //===============================================================================================
    // Electricity Tower Level 3 //==================================================================
    //===============================================================================================
    "electricity_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "fire"
            "2"     "light"
        }               
        "Damage"                    "0"
        "DamageType"                "fire"
        "ScriptClass"               "ElectricityTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1100"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "1000"
        "Model"                     "models/fof_psychonic_prop/fof_psychonic_prop.vmdl"
        "ModelScale"                "0.9"
        "UpgradeIcon"               "towers/electricty_tower_conjure_lightning"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "3"
            "light"     "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Flame Tower Level 1 //=======================================================================
    //===============================================================================================
    "flame_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "fire"
            "2"     "nature"
        }               
        "Damage"                    "33"
        "DamageType"                "fire"
        "ScriptClass"               "FlameTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_phoenix"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/flame_tower_sunburn"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "flame_tower_2"
            "2"         "quake_tower"
            "3"         "impulse_tower"
            "4"         "jinx_tower"
            "5"         "nova_tower"
        }
    }

    //===============================================================================================
    // Flame Tower Level 2 //=======================================================================
    //===============================================================================================
    "flame_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "fire"
            "2"     "nature"
        }               
        "Damage"                    "165"
        "DamageType"                "fire"
        "ScriptClass"               "FlameTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_phoenix"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "towers/flame_tower_sunburn"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "2"
            "nature"    "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "flame_tower_3"
        }
    }

    //===============================================================================================
    // Flame Tower Level 3 //=======================================================================
    //===============================================================================================
    "flame_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "fire"
            "2"     "nature"
        }               
        "Damage"                    "825"
        "DamageType"                "fire"
        "ScriptClass"               "FlameTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_phoenix"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.9"
        "UpgradeIcon"               "towers/flame_tower_sunburn"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "3"
            "nature"    "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Vapor Tower Level 1 //========================================================================
    //===============================================================================================
    "vapor_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "fire"
            "2"     "water"
        }               
        "Damage"                    "0"
        "DamageType"                "water"
        "ScriptClass"               "VaporTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "morphling_adaptive_strike"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "vapor_tower_2"
            "2"         "windstorm_tower"
            "3"         "impulse_tower"
            "4"         "haste_tower"
            "5"         "erosion_tower"
        }
    }

    //===============================================================================================
    // Vapor Tower Level 2 //========================================================================
    //===============================================================================================
    "vapor_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "fire"
            "2"     "water"
        }               
        "Damage"                    "0"
        "DamageType"                "water"
        "ScriptClass"               "VaporTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "morphling_adaptive_strike"
        "BuildTime"                 "3"
        
        "Requirements"
        {
            "fire"      "2"
            "water"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "vapor_tower_3"
        }
    }

    //===============================================================================================
    // Vapor Tower Level 3 //========================================================================
    //===============================================================================================
    "vapor_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "fire"
            "2"     "water"
        }               
        "Damage"                    "0"
        "DamageType"                "water"
        "ScriptClass"               "VaporTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "morphling_adaptive_strike"
        "BuildTime"                 "3"

        "Requirements"
        {
            "fire"      "3"
            "water"     "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Poison Tower Level 1 //========================================================================
    //===============================================================================================
    "poison_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "dark"
            "2"     "water"
        }
        "Damage"                    "100"
        "DamageType"                "water"
        "ScriptClass"               "PoisonTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_viper/viper_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_viper"
        "SoundSet"                  "Hero_VenomancerWard"
        "ProjectileSpeed"           "1800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.7"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "towers/poison_tower_contamination"
        "BuildTime"                 "3"

        "Requirements"
        {
            "dark"      "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "poison_tower_2"
            "2"         "muck_tower"
            "3"         "flooding_tower"
            "4"         "hail_tower"
            "5"         "erosion_tower"
        }
    }

    //===============================================================================================
    // Poison Tower Level 2 //========================================================================
    //===============================================================================================
    "poison_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "dark"
            "2"     "water"
        }
        "Damage"                    "500"
        "DamageType"                "water"
        "ScriptClass"               "PoisonTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_viper/viper_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_viper"
        "SoundSet"                  "Hero_VenomancerWard"
        "ProjectileSpeed"           "1800"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.775"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "towers/poison_tower_contamination"
        "BuildTime"                 "3"

        "Requirements"
        {
            "dark"      "2"
            "water"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "poison_tower_3"
        }
    }

    //===============================================================================================
    // Poison Tower Level 3 //========================================================================
    //===============================================================================================
    "poison_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "dark"
            "2"     "water"
        }
        "Damage"                    "2500"
        "DamageType"                "water"
        "ScriptClass"               "PoisonTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_venomancer/venomancer_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_venomancer"
        "SoundSet"                  "Hero_VenomancerWard"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/good_statue008.mdl"
        "ModelScale"                "0.85"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "towers/poison_tower_contamination"
        "BuildTime"                 "3"

        "Requirements"
        {
            "dark"      "3"
            "water"     "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Life Tower Level 1 //========================================================================
    //===============================================================================================
    "life_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "light"
            "2"     "nature"
        }
        "Damage"                    "93"
        "DamageType"                "nature"
        "ScriptClass"               "LifeTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_wisp"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/life_tower_afterlife"
        "BuildTime"                 "3"

        "Requirements"
        {
            "light"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "life_tower_2"
            "2"         "enchantment_tower"
            "3"         "obliteration_tower"
            "4"         "torrent_tower"
            "5"         "nova_tower"
        }
    }

    //===============================================================================================
    // Life Tower Level 2 //========================================================================
    //===============================================================================================
    "life_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "light"
            "2"     "nature"
        }
        "Damage"                    "465"
        "DamageType"                "nature"
        "ScriptClass"               "LifeTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_wisp"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.825"
        "UpgradeIcon"               "towers/life_tower_afterlife"
        "BuildTime"                 "3"

        "Requirements"
        {
            "light"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "life_tower_3"
        }
    }

    //===============================================================================================
    // Life Tower Level 3 //========================================================================
    //===============================================================================================
    "life_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "light"
            "2"     "nature"
        }
        "Damage"                    "2325"
        "DamageType"                "nature"
        "ScriptClass"               "LifeTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_wisp"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.9"
        "UpgradeIcon"               "towers/life_tower_afterlife"
        "BuildTime"                 "3"

        "Requirements"
        {
            "light"     "3"
            "nature"    "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Hydro Tower Level 1 //========================================================================
    //===============================================================================================
    "hydro_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "water"
            "2"     "earth"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "earth"
        "ScriptClass"               "HydroTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "725"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "puck_illusory_orb"
        "BuildTime"                 "3"

        "Requirements"
        {
            "water"     "1"
            "earth"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "hydro_tower_2"
            "2"         "muck_tower"
            "3"         "ephemeral_tower"
            "4"         "haste_tower"
            "5"         "polar_tower"
        }
    }

    //===============================================================================================
    // Hydro Tower Level 2 //========================================================================
    //===============================================================================================
    "hydro_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "water"
            "2"     "earth"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "earth"
        "ScriptClass"               "HydroTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "725"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.825"
        "UpgradeIcon"               "puck_illusory_orb"
        "BuildTime"                 "3"

        "Requirements"
        {
            "water"     "2"
            "earth"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "hydro_tower_3"
        }
    }

    //===============================================================================================
    // Hydro Tower Level 3 //========================================================================
    //===============================================================================================
    "hydro_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "water"
            "2"     "earth"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "earth"
        "ScriptClass"               "HydroTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "725"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.9"
        "UpgradeIcon"               "puck_illusory_orb"
        "BuildTime"                 "3"

        "Requirements"
        {
            "water"     "3"
            "earth"     "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Trickery Tower Level 1 //=====================================================================
    //===============================================================================================
    "trickery_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "light"
            "2"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "210"
        "DamageType"                "light"
        "ScriptClass"               "TrickeryTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "modifier_illusion"
        "BuildTime"                 "3"

        "Requirements"
        {
            "light"     "1"
            "dark"      "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "trickery_tower_2"
            "2"         "laser_tower"
            "3"         "hail_tower"
            "4"         "runic_tower"
            "5"         "obliteration_tower"
        }
    }

    //===============================================================================================
    // Trickery Tower Level 2 //=====================================================================
    //===============================================================================================
    "trickery_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "light"
            "2"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "1050"
        "DamageType"                "light"
        "ScriptClass"               "TrickeryTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.825"
        "UpgradeIcon"               "modifier_illusion"
        "BuildTime"                 "3"

        "Requirements"
        {
            "light"     "2"
            "dark"      "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "trickery_tower_3"
        }
    }

    //===============================================================================================
    // Trickery Tower Level 3 //=====================================================================
    //===============================================================================================
    "trickery_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "light"
            "2"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "5250"
        "DamageType"                "light"
        "ScriptClass"               "TrickeryTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_keeper_of_the_light"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.9"
        "UpgradeIcon"               "modifier_illusion"
        "BuildTime"                 "3"

        "Requirements"
        {
            "light"     "3"
            "dark"      "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Gunpowder Tower Level 1 //====================================================================
    //===============================================================================================
    "gunpowder_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "earth"
            "2"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "earth"
        "ScriptClass"               "GunpowderTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_techies/techies_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_techies"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "techies_suicide"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "1"
            "dark"      "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "gunpowder_tower_2"
            "2"         "muck_tower"
            "3"         "laser_tower"
            "4"         "flamethrower_tower"
            "5"         "roots_tower"
        }
    }

    //===============================================================================================
    // Gunpowder Tower Level 2 //====================================================================
    //===============================================================================================
    "gunpowder_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "earth"
            "2"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "earth"
        "ScriptClass"               "GunpowderTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_techies/techies_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_techies"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.825"
        "UpgradeIcon"               "techies_suicide"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "2"
            "dark"      "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "gunpowder_tower_3"
        }
    }

    //===============================================================================================
    // Gunpowder Tower Level 3 //====================================================================
    //===============================================================================================
    "gunpowder_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "earth"
            "2"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "earth"
        "ScriptClass"               "GunpowderTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_techies/techies_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_techies"
        "ProjectileSpeed"           "800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.9"
        "UpgradeIcon"               "techies_suicide"
        "BuildTime"                 "3"

        "Requirements"
        {
            "earth"     "3"
            "dark"      "3"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Ice Tower Level 1 //==========================================================================
    //===============================================================================================
    "ice_tower"
    {
        "Level"                     "1"
        "Cost"                      "325"
        "TotalCost"                 "500"
        "Element"
        {
            "1"     "water"
            "2"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "light"
        "ScriptClass"               "IceTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "ancient_apparition_ice_blast"
        "BuildTime"                 "3"

        "Requirements"
        {
            "water"     "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "5"
            "1"         "ice_tower_2"
            "2"         "windstorm_tower"
            "3"         "hail_tower"
            "4"         "torrent_tower"
            "5"         "polar_tower"
        }
    }

    //===============================================================================================
    // Ice Tower Level 2 //==========================================================================
    //===============================================================================================
    "ice_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "750"
        "TotalCost"                 "1250"
        "Element"
        {
            "1"     "water"
            "2"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "light"
        "ScriptClass"               "IceTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "ancient_apparition_ice_blast"
        "BuildTime"                 "3"

        "Requirements"
        {
            "water"     "2"
            "light"     "2"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "ice_tower_3"
        }
    }

    //===============================================================================================
    // Ice Tower Level 3 //==========================================================================
    //===============================================================================================
    "ice_tower_3"
    {
        "Level"                     "3"
        "Cost"                      "1900"
        "TotalCost"                 "3150"
        "Element"
        {
            "1"     "water"
            "2"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "light"
        "ScriptClass"               "IceTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "ancient_apparition_ice_blast"
        "BuildTime"                 "3"

        "Requirements"
        {
            "water"     "3"
            "light"     "3"
        }
        "Upgrades"
        {
        }
    }


    //===============================================================================================
    // Muck Tower Level 1 //=========================================================================
    //===============================================================================================
    "muck_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "600"
        "DamageType"                "earth"
        "ScriptClass"               "MuckTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_venomancer/venomancer_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_venomancer"
        "ProjectileSpeed"           "1800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"
        "UpgradeIcon"               "bristleback_viscous_nasal_goo"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "earth"     "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "muck_tower_2"
        }
    }

    //===============================================================================================
    // Muck Tower Level 2 //=========================================================================
    //===============================================================================================
    "muck_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "3000"
        "DamageType"                "earth"
        "ScriptClass"               "MuckTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_venomancer/venomancer_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_venomancer"
        "ProjectileSpeed"           "1800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.85"
        "AOE_Full"                  "150"
        "AOE_Half"                  "300"
        "UpgradeIcon"               "bristleback_viscous_nasal_goo"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "earth"     "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Gold Tower Level 1 //=========================================================================
    //===============================================================================================
    "gold_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "3000"
        "DamageType"                "earth"
        "ScriptClass"               "GoldTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1.5"
        "ProjectileModel"           "particles/units/heroes/hero_venomancer/venomancer_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_venomancer"
        "ProjectileSpeed"           "1800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/gold_tower_arbitrage"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "1"
            "earth"     "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "gold_tower_2"
        }
    }

    //===============================================================================================
    // Gold Tower Level 2 //=========================================================================
    //===============================================================================================
    "gold_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "15000"
        "DamageType"                "earth"
        "ScriptClass"               "GoldTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1.5"
        "ProjectileModel"           "particles/units/heroes/hero_venomancer/venomancer_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_venomancer"
        "ProjectileSpeed"           "1800"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/gold_tower_arbitrage"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "2"
            "earth"     "2"
            "light"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Windstorm Tower Level 1 //====================================================================
    //===============================================================================================
    "windstorm_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "fire"
            "2"     "light"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "water"
        "ScriptClass"               "WindstormTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "0"
        "AttackAcquisitionRange"    "0"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/windstorm_tower_tornado"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "1"
            "light"     "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "windstorm_tower_2"
        }
    }

    //===============================================================================================
    // Windstorm Tower Level 2 //====================================================================
    //===============================================================================================
    "windstorm_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "fire"
            "2"     "light"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "water"
        "ScriptClass"               "WindstormTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "0"
        "AttackAcquisitionRange"    "0"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/windstorm_tower_tornado"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "2"
            "light"     "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Quake Tower Level 1 //========================================================================
    //===============================================================================================
    "quake_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "600"
        "DamageType"                "earth"
        "ScriptClass"               "QuakeTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "earthshaker_aftershock"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "1"
            "earth"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "quake_tower_2"
        }
    }

    //===============================================================================================
    // Quake Tower Level 2 //========================================================================
    //===============================================================================================
    "quake_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "fire"
            "2"     "earth"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "3000"
        "DamageType"                "earth"
        "ScriptClass"               "QuakeTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "500"
        "AttackAcquisitionRange"    "500"
        "AttackRate"                "0.66"
        "ProjectileModel"           "particles/units/heroes/hero_furion/furion_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_furion"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "earthshaker_aftershock"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "2"
            "earth"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Enchantment Tower Level 1 //==================================================================
    //===============================================================================================
    "enchantment_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "earth"
            "2"     "light"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "279"
        "DamageType"                "nature"
        "ScriptClass"               "EnchantmentTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_invoker"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "leshrac_diabolic_edict"
        "BuildTime"                 "4"

        "Requirements"
        {
            "earth"     "1"
            "light"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "enchantment_tower_2"
        }
    }

    //===============================================================================================
    // Enchantment Tower Level 2 //==================================================================
    //===============================================================================================
    "enchantment_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "earth"
            "2"     "light"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "1395"
        "DamageType"                "nature"
        "ScriptClass"               "EnchantmentTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_invoker/invoker_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_invoker"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "leshrac_diabolic_edict"
        "BuildTime"                 "4"

        "Requirements"
        {
            "earth"     "2"
            "light"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Flooding Tower Level 1 //=====================================================================
    //===============================================================================================
    "flooding_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "water"
            "2"     "nature"
            "3"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "950"
        "DamageType"                "water"
        "ScriptClass"               "FloodingTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "BuildTime"                 "4"
        "UpgradeIcon"               "naga_siren_rip_tide"

        "Requirements"
        {
            "water"     "1"
            "nature"    "1"
            "dark"      "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "flooding_tower_2"
        }
    }

    //===============================================================================================
    // Flooding Tower Level 2 //=====================================================================
    //===============================================================================================
    "flooding_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "water"
            "2"     "nature"
            "3"     "dark"
        }
        "SoundSet"                  ""
        "Damage"                    "4750"
        "DamageType"                "water"
        "ScriptClass"               "FloodingTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "BuildTime"                 "4"
        "UpgradeIcon"               "naga_siren_rip_tide"

        "Requirements"
        {
            "water"     "2"
            "nature"    "2"
            "dark"      "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Laser Tower Level 1 //========================================================================
    //===============================================================================================
    "laser_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "6000"
        "DamageType"                "light"
        "ScriptClass"               "LaserTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_tinker"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "tinker_laser"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "earth"     "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "laser_tower_2"
        }
    }

    //===============================================================================================
    // Laser Tower Level 2 //========================================================================
    //===============================================================================================
    "laser_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "30000"
        "DamageType"                "light"
        "ScriptClass"               "LaserTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_tinker"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "tinker_laser"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "earth"     "2"
            "light"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Hail Tower Level 1 //=========================================================================
    //===============================================================================================
    "hail_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "light"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "390"
        "DamageType"                "light"
        "ScriptClass"               "HailTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_ancient_apparition"
        "ProjectileModel"           "particles/units/heroes/hero_ancient_apparition/ancient_apparition_base_attack.vpcf"
        "ProjectileSpeed"           "1250"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "crystal_maiden_freezing_field"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "light"     "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "hail_tower_2"
        }
    }

    //===============================================================================================
    // Hail Tower Level 2 //=========================================================================
    //===============================================================================================
    "hail_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "light"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "1950"
        "DamageType"                "light"
        "ScriptClass"               "HailTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_ancient_apparition"
        "ProjectileModel"           "particles/units/heroes/hero_ancient_apparition/ancient_apparition_base_attack.vpcf"
        "ProjectileSpeed"           "1250"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "crystal_maiden_freezing_field"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "light"     "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Runic Tower Level 1 //========================================================================
    //===============================================================================================
    "runic_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "400"
        "DamageType"                "dark"
        "ScriptClass"               "RunicTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.66"
        "particle_folder"           "particles/units/heroes/hero_visage"
        "ProjectileModel"           "particles/units/heroes/hero_visage/visage_base_attack.vpcf"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "AOE_Full"                  "150"
        "AOE_Half"                  "250"
        "UpgradeIcon"               "visage_gravekeepers_cloak"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "fire"      "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "runic_tower_2"
        }
    }

    //===============================================================================================
    // Runic Tower Level 2 //========================================================================
    //===============================================================================================
    "runic_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "2000"
        "DamageType"                "dark"
        "ScriptClass"               "RunicTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "0.66"
        "particle_folder"           "particles/units/heroes/hero_visage"
        "ProjectileModel"           "particles/units/heroes/hero_visage/visage_base_attack.vpcf"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "AOE_Full"                  "150"
        "AOE_Half"                  "250"
        "UpgradeIcon"               "visage_gravekeepers_cloak"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "fire"      "2"
            "light"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Impulse Tower Level 1 //========================================================================
    //===============================================================================================
    "impulse_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "nature"
            "2"     "fire"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "nature"
        "ScriptClass"               "ImpulseTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_enchantress"
        "ProjectileModel"           "particles/units/heroes/hero_enchantress/enchantress_impetus.vpcf"
        "ProjectileSpeed"           "2000"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "enchantress_impetus"
        "BuildTime"                 "4"

        "Requirements"
        {
            "nature"    "1"
            "fire"      "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "impulse_tower_2"
        }
    }

    //===============================================================================================
    // Impulse Tower Level 2 //========================================================================
    //===============================================================================================
    "impulse_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "nature"
            "2"     "fire"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "nature"
        "ScriptClass"               "ImpulseTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1375"
        "AttackAcquisitionRange"    "1375"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_enchantress"
        "ProjectileModel"           "particles/units/heroes/hero_enchantress/enchantress_impetus.vpcf"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "enchantress_impetus"
        "BuildTime"                 "4"

        "Requirements"
        {
            "nature"    "2"
            "fire"      "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Obliteration Tower Level 1 //=================================================================
    //===============================================================================================
    "obliteration_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "light"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "2500"
        "DamageType"                "dark"
        "ScriptClass"               "ObliterationTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1.5"
        "particle_folder"           "particles/units/heroes/hero_obsidian_destroyer"
        "ProjectileModel"           ""
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "obsidian_destroyer_sanity_eclipse"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "light"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "obliteration_tower_2"
        }
    }

    //===============================================================================================
    // Obliteration Tower Level 2 //=================================================================
    //===============================================================================================
    "obliteration_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "light"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "12500"
        "DamageType"                "dark"
        "ScriptClass"               "ObliterationTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "1000"
        "AttackAcquisitionRange"    "1000"
        "AttackRate"                "1.5"
        "particle_folder"           "particles/units/heroes/hero_obsidian_destroyer"
        "ProjectileModel"           ""
        "ProjectileSpeed"           "1000"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "obsidian_destroyer_sanity_eclipse"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "light"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Ephemeral Tower Level 1 //====================================================================
    //===============================================================================================
    "ephemeral_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "earth"
            "2"     "nature"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "1800"
        "DamageType"                "nature"
        "ScriptClass"               "EphemeralTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_windrunner"
        "ProjectileModel"           "particles/units/heroes/hero_windrunner/windrunner_base_attack.vpcf"
        "ProjectileSpeed"           "2400"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/ephemeral_tower_phasing"
        "BuildTime"                 "4"

        "Requirements"
        {
            "earth"     "1"
            "nature"    "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "ephemeral_tower_2"
        }
    }

    //===============================================================================================
    // Ephemeral Tower Level 2 //====================================================================
    //===============================================================================================
    "ephemeral_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "earth"
            "2"     "nature"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "9000"
        "DamageType"                "nature"
        "ScriptClass"               "EphemeralTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.31"
        "particle_folder"           "particles/units/heroes/hero_windrunner"
        "ProjectileModel"           "particles/units/heroes/hero_windrunner/windrunner_base_attack.vpcf"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/ephemeral_tower_phasing"
        "BuildTime"                 "4"

        "Requirements"
        {
            "earth"     "2"
            "nature"    "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Flamethrower Tower Level 1 //=================================================================
    //===============================================================================================
    "flamethrower_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "fire"
        }
        "SoundSet"                  ""
        "Damage"                    "300"
        "DamageType"                "fire"
        "ScriptClass"               "FlamethrowerTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.66"
        "particle_folder"           "particles/units/heroes/hero_batrider"
        "ProjectileModel"           "particles/units/heroes/hero_batrider/batrider_base_attack.vpcf"
        "ProjectileSpeed"           "2500"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "AOE_Half"                  "300"
        "AOE_Full"                  "150"
        "UpgradeIcon"               "batrider_sticky_napalm"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "earth"     "1"
            "fire"      "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "flamethrower_tower_2"
        }
    }

    //===============================================================================================
    // Flamethrower Tower Level 2 //=================================================================
    //===============================================================================================
    "flamethrower_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "fire"
        }
        "SoundSet"                  ""
        "Damage"                    "1500"
        "DamageType"                "fire"
        "ScriptClass"               "FlamethrowerTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "0.66"
        "particle_folder"           "particles/units/heroes/hero_batrider"
        "ProjectileModel"           "particles/units/heroes/hero_batrider/batrider_base_attack.vpcf"
        "ProjectileSpeed"           "2500"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "AOE_Half"                  "300"
        "AOE_Full"                  "150"
        "UpgradeIcon"               "batrider_sticky_napalm"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "earth"     "2"
            "fire"      "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Haste Tower Level 1 //========================================================================
    //===============================================================================================
    "haste_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "earth"
            "2"     "fire"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "1020"
        "DamageType"                "fire"
        "ScriptClass"               "HasteTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_batrider"
        "ProjectileModel"           "particles/units/heroes/hero_batrider/batrider_base_attack.vpcf"
        "ProjectileSpeed"           "1200"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "troll_warlord_fervor"
        "BuildTime"                 "4"

        "Requirements"
        {
            "earth"     "1"
            "fire"      "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "haste_tower_2"
        }
    }

    //===============================================================================================
    // Haste Tower Level 2 //========================================================================
    //===============================================================================================
    "haste_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "earth"
            "2"     "fire"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "5100"
        "DamageType"                "fire"
        "ScriptClass"               "HasteTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "particle_folder"           "particles/units/heroes/hero_batrider"
        "ProjectileModel"           "particles/units/heroes/hero_batrider/batrider_base_attack.vpcf"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "troll_warlord_fervor"
        "BuildTime"                 "4"

        "Requirements"
        {
            "earth"     "2"
            "fire"      "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Torrent Tower Level 1 //======================================================================
    //===============================================================================================
    "torrent_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "water"
            "2"     "nature"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "420"
        "DamageType"                "water"
        "ScriptClass"               "TorrentTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.75"
        "UpgradeIcon"               "towers/torrent_tower_douse"
        "BuildTime"                 "4"

        "Requirements"
        {
            "water"     "1"
            "nature"    "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "torrent_tower_2"
        }
    }

    //===============================================================================================
    // Torrent Tower Level 2 //======================================================================
    //===============================================================================================
    "torrent_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "water"
            "2"     "nature"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "2100"
        "DamageType"                "water"
        "ScriptClass"               "TorrentTower"
        "TowerType"                 "Normal"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "0.31"
        "ProjectileModel"           "particles/units/heroes/hero_morphling/morphling_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_morphling"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "towers/torrent_tower_douse"
        "BuildTime"                 "4"

        "Requirements"
        {
            "water"     "2"
            "nature"    "2"
            "light"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Nova Tower Level 1 //======================================================================
    //===============================================================================================
    "nova_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "fire"
            "2"     "nature"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "light"
        "ScriptClass"               "NovaTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           "particles/units/heroes/hero_phoenix"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/phoenix/phoenix_egg.vmdl"
        "ModelScale"                "0.6"
        "UpgradeIcon"               "phoenix_supernova"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "1"
            "nature"    "1"
            "light"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "nova_tower_2"
        }
    }

    //===============================================================================================
    // Nova Tower Level 2 //======================================================================
    //===============================================================================================
    "nova_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "fire"
            "2"     "nature"
            "3"     "light"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "light"
        "ScriptClass"               "NovaTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1.5"
        "ProjectileModel"           ""
        "particle_folder"           "particles/units/heroes/hero_phoenix"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/phoenix/phoenix_egg.vmdl"
        "ModelScale"                "0.7"
        "UpgradeIcon"               "phoenix_supernova"
        "BuildTime"                 "4"

        "Requirements"
        {
            "fire"      "2"
            "nature"    "2"
            "light"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Polar Tower Level 1 //========================================================================
    //===============================================================================================
    "polar_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "water"
            "2"     "light"
            "3"     "earth"
        }
        "SoundSet"                  ""
        "Damage"                    "900"
        "DamageType"                "earth"
        "ScriptClass"               "PolarTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_lich/lich_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_lich"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.7"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "crystal_maiden_crystal_nova"
        "BuildTime"                 "4"

        "Requirements"
        {
            "water"     "1"
            "light"     "1"
            "earth"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "polar_tower_2"
        }
    }

    //===============================================================================================
    // Polar Tower Level 2 //========================================================================
    //===============================================================================================
    "polar_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "water"
            "2"     "light"
            "3"     "earth"
        }
        "SoundSet"                  ""
        "Damage"                    "4500"
        "DamageType"                "earth"
        "ScriptClass"               "PolarTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_lich/lich_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_lich"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.7"
        "AOE_Full"                  "100"
        "AOE_Half"                  "200"
        "UpgradeIcon"               "crystal_maiden_crystal_nova"
        "BuildTime"                 "4"

        "Requirements"
        {
            "water"     "2"
            "light"     "2"
            "earth"     "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Jinx Tower Level 1 //=========================================================================
    //===============================================================================================
    "jinx_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "2100"
        "DamageType"                "dark"
        "ScriptClass"               "JinxTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_witchdoctor/witchdoctor_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_witchdoctor"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/witchdoctor/witchdoctor_ward.vmdl"
        "ModelScale"                "0.85"
        "UpgradeIcon"               "witch_doctor_maledict"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "fire"      "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "jinx_tower_2"
        }
    }

    //===============================================================================================
    // Jinx Tower Level 2 //=========================================================================
    //===============================================================================================
    "jinx_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "10500"
        "DamageType"                "dark"
        "ScriptClass"               "JinxTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_witchdoctor/witchdoctor_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_witchdoctor"
        "ProjectileSpeed"           "900"
        "Model"                     "models/heroes/witchdoctor/witchdoctor_ward.vmdl"
        "ModelScale"                "0.95"
        "UpgradeIcon"               "witch_doctor_maledict"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "fire"      "2"
            "nature"    "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Roots Tower Level 1 //=========================================================================
    //===============================================================================================
    "roots_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "nature"
        "ScriptClass"               "RootsTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.7"
        "UpgradeIcon"               "treant_leech_seed"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "earth"     "1"
            "nature"    "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "roots_tower_2"
        }
    }

    //===============================================================================================
    // Roots Tower Level 2 //=========================================================================
    //===============================================================================================
    "roots_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "earth"
            "3"     "nature"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "nature"
        "ScriptClass"               "RootsTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "750"
        "AttackAcquisitionRange"    "750"
        "AttackRate"                "1"
        "ProjectileModel"           ""
        "particle_folder"           ""
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "UpgradeIcon"               "treant_leech_seed"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "earth"     "2"
            "nature"    "2"
        }
        "Upgrades"
        {
        }
    }

    //===============================================================================================
    // Erosion Tower Level 1 //======================================================================
    //===============================================================================================
    "erosion_tower"
    {
        "Level"                     "1"
        "Cost"                      "1000"
        "TotalCost"                 "1500"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "fire"
        "ScriptClass"               "ErosionTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_warlock/warlock_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_warlock"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.7"
        "AOE_Full"                  "400"
        "AOE_Half"                  "400"
        "UpgradeIcon"               "towers/erosion_tower_acid_attack"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "1"
            "fire"      "1"
            "water"     "1"
        }
        "Upgrades"
        {
            "Count"     "1"
            "1"         "erosion_tower_2"
        }
    }

    //===============================================================================================
    // Erosion Tower Level 2 //======================================================================
    //===============================================================================================
    "erosion_tower_2"
    {
        "Level"                     "2"
        "Cost"                      "3500"
        "TotalCost"                 "5000"
        "Element"
        {
            "1"     "dark"
            "2"     "fire"
            "3"     "water"
        }
        "SoundSet"                  ""
        "Damage"                    "0"
        "DamageType"                "fire"
        "ScriptClass"               "ErosionTower"
        "TowerType"                 "Support"
        "HasAbilityDesc"            "1"
        "AttackRange"               "625"
        "AttackAcquisitionRange"    "625"
        "AttackRate"                "1"
        "ProjectileModel"           "particles/units/heroes/hero_phoenix/phoenix_base_attack.vpcf"
        "particle_folder"           "particles/units/heroes/hero_phoenix"
        "ProjectileSpeed"           "900"
        "Model"                     "models/props_structures/tower_good.mdl"
        "ModelScale"                "0.8"
        "AOE_Full"                  "400"
        "AOE_Half"                  "400"
        "UpgradeIcon"               "towers/erosion_tower_acid_attack"
        "BuildTime"                 "4"

        "Requirements"
        {
            "dark"      "2"
            "fire"      "2"
            "water"     "2"
        }
        "Upgrades"
        {
        }
    }
}